### ISSUE TITLE
Offset not being set/read correctly

### ISSUE THREAD

**Issue by rajatjai** [snowflakedb/snowflake-kafka-connector#100]
- Connector version : 1.0.0
- Kafka Connect confluent-5.3.0-2.12

Hi,

We are facing multiple issues related to reliability of messages being sent to snowflake with the connector. Raising ticket for one such issue.

Problem:
- We stopped the job and reset the offset to an earlier one to reload some messages again. However, got this warning multiple times and missed more messages than before.

> [2020-02-17 17:10:31,751] WARN WorkerSinkTask{id=snowflake_gis_stats_v5-0} Ignoring invalid task provided offset gis-stats-v5-0/OffsetAndMetadata{offset=9223372036854775807, leaderEpoch=null, metadata=''} -- not yet consumed, taskOffset=9223372036854775807 currentOffset=8825666 (org.apache.kafka.connect.runtime.WorkerSinkTask:416)

This does not happen often but we encountered it yesterday. The `taskOffset` looks weird.

**Comment by Stormhand** [comment]
This happen to me too with connector 1.1.0 and Kafka confluent 5.4

**Comment by bsmith-optoro** [comment]
We are seeing this as well in connector version 1.3.0, the most recent version we currently have running.  The taskOffset is the same, 9223372036854775807... the max value of a signed 64 bit integer.

**Comment by sfc-gh-zli** [comment]
Version 1.4.3 fixed many previous bugs related with offset commitments. Please consider upgrading.
