### ISSUE TITLE
Missed messages on restarting connect job

### ISSUE THREAD

**Issue by rajatjai** [snowflakedb/snowflake-kafka-connector#101]
- Connector version : 1.0.0
- Kafka Connect confluent-5.3.0-2.12

Scenario:
- Kafka connect running in K8s in standalone mode
- One topic -> one consumer group 
- Kubernetes CronJob (restarts every day - once)
- `buffer.count.records=400000`
- `buffer.flush.time=1800`

While restarting, sometimes the consumer group rebalances and we miss the last 1800(`buffer.flush.time`) seconds data.

Message:

> [2020-02-17 05:30:34,146] INFO [Consumer clientId=connector-consumer-snowflake_gis_stats_v5-1, groupId=connect-snowflake_gis_stats_v5] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:936)

Whenever we encounter this message while restarting, we miss the messages collected in the last 1800(`buffer.flush.time`) seconds.

**Comment by sfc-gh-zli** [comment]
version 1.4.0 should have fixed this issue.
