### ISSUE TITLE
Release using the new ingest-sdk library 

### ISSUE THREAD

**Issue by islobodch** [snowflakedb/snowflake-kafka-connector#104]
Hi. We are using the kafka-connector and the current release is based on the ingest-sdk library which had a bug fixed in its [latest release](https://repo.maven.apache.org/maven2/net/snowflake/snowflake-ingest-sdk/0.9.7/). Correspondingly, we need a release of kafka-connector which uses this library.

**Comment by binglihub** [comment]
fixed https://github.com/snowflakedb/snowflake-kafka-connector/pull/106
