### ISSUE TITLE
Jar 1.0.2 Class not found exception BouncyCastleFipsProvider

### ISSUE THREAD

**Issue by harshmeetrakkar** [snowflakedb/snowflake-kafka-connector#108]
Hi,

Getting below exception when using an encrypted key. Added bc-fips and changed like below to add the required classes.

### ERROR:

`"Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider"`
 

Added bc-fips and changed like below to add the required classes.

### CHANGES IN POM:
```
<dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-fips</artifactId>
            <version>1.0.3</version>
            <!--scope>provided</scope-->
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bc-fips</artifactId>
            <version>1.0.2</version>
            <!--scope>provided</scope-->
        </dependency>
```

### ERROR AFTER ADDING bc-fips:

```
2020-03-13 17:17:12,296 ERROR WorkerConnector{id=snowflake_sink_messages} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector) [pool-10-thread-1
]
org.bouncycastle.crypto.fips.FipsOperationError: org.bouncycastle.crypto.fips.FipsOperationError: Module checksum failed: expected [d68017e6f45512a51a862c77e4fa2348d0d24d816bc3f76fcf30375052216e86] 
got [f4fd53410d9b8c9c253ec0f349c26f6b19c0c7befabd5d09be48cc857661fc74]
```

**Comment by harshmeetrakkar** [comment]
My mistake. fixed it now

**Comment by acristu** [comment]
@harshmeetrakkar can you please provide your fix?

**Comment by abhishekkh** [comment]
@acristu @harshmeetrakkar running into the same error with the checksum mismatch. Whats the fix?

**Comment by harshmeetrakkar** [comment]
@abhishekkh I had added the BouncyCastle jars into the target folders and also added in jenkins pipeline to fetch the jars. I hope it gives you an idea how you can solve your problem. Its been a very longtime since I worked with this so checked old commits and added these details.

Added in Docker file
`COPY ./target/bc*.jar /opt/kafka/plugins/snowflake/`

Added in my jenkins pipeline to fetch jars from the Artifact management repository
`sh 'mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -DrepoUrl=' + NEXUS_RELEASE_REPOSITORY + ' -Dartifact=org.bouncycastle:bc-fips:1.0.1 -Ddest=target/bc-fips-1.0.1.jar'
sh 'mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -DrepoUrl=' + NEXUS_RELEASE_REPOSITORY + ' -Dartifact=org.bouncycastle:bcpkix-fips:1.0.3 -Ddest=target/bcpkix-fips-1.0.3.jar'
stash includes: '**/target/snowflake-kafka-connector*.jar', name: 'snowflake-kafka-connector'
stash includes: '**/target/bc*.jar', name: 'bouncy-castle'`

Unstashed the bouncy-castle jar before building the final image in jenkins pipeline
`unstash name: 'bouncy-castle'`
