### ISSUE TITLE
Record any Kafka record headers on a message into `record_metadata`

### ISSUE THREAD

**Issue by yarmiganosca** [snowflakedb/snowflake-kafka-connector#12]
We use a couple Kafka record headers, and we'd like them to show up in Snowflake. It would be great if the connector could write any message headers (https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers) present on a Kafka message to the `record_metadata` field in the target table.

**Comment by yarmiganosca** [comment]
Was this closed because it was satisfied by a PR?

**Comment by binglihub** [comment]
@yarmiganosca sorry, I closed the wrong issue. Anyway, I am working on it. A quick question, do you guys include Struct, Array, and Map type data in the headers?

**Comment by yarmiganosca** [comment]
No problem. Right now we're only putting primitive types as values in the message headers. No collection types or structs so far. I also can't currently think of a requirement that would cause us to start including collection or struct types in message headers.

**Comment by binglihub** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/commit/b6d141ba6547ccb6668c3739a73823b40edcfbd3
