### ISSUE TITLE
String Format Decimals Converting To Unknown Codes

### ISSUE THREAD

**Issue by naga-kondapaturi-zefr** [snowflakedb/snowflake-kafka-connector#122]
We are using SnowflakeAvroConverter with defined schema registry. The connector is decoding these values to unknown string formats when storing data in Snowflake. We are using 1.0.0 (in prod) but the latest on local seems to give the same error. We tried available sql functions within snowflake to decode these values but no use. The data is in an unusable state.

For e.g.
`"0.2700"` in Kafka stored in Snowflake DB as `"\n"`
`"0.3500"` in Kafka stored in Snowflake DB as `"\r¬"`

Schema registry definition:

    {
      "name": "percent_field",
      "type": [
        "null",
        {
          "type": "bytes",
          "scale": 4,
          "precision": 64,
          "connect.version": 1,
          "connect.parameters": {
            "scale": "4"
          },
          "connect.name": "org.apache.kafka.connect.data.Decimal",
          "logicalType": "decimal"
        }
      ],
      "default": null
    },

**Comment by sfc-gh-zli** [comment]
please try to upgrade to 1.4.0, this should have been fixed in https://github.com/snowflakedb/snowflake-kafka-connector/pull/131

**Comment by mjreiss** [comment]
@sfc-gh-zli Is this issue still ongoing? We are currently on version 1.4.1, and all messages are going into snowflake with this unusable format.

**Comment by drobert** [comment]
Looking at the referenced PR (#131) I commented on a few things that look like they may be contributing: https://github.com/snowflakedb/snowflake-kafka-connector/pull/131/files#r463259581

Notably:
- the conversion code casts the byte array to `BigDecimal` without specifying scale or precision
- json Number types don't support arbitrary precision. I would expect only a String representation to be able to represent a BigDecimal accurately

**Comment by sfc-gh-zli** [comment]
This is a bug inside SnowflakeAvroConverter. We internally used `org.apache.avro.generic.GenericDatumReader` to convert AVRO bytes to JSON in SnowflakeAvroConverter, which does not handle byte array and BigDecimal well. I have a walk around:

1. change your `value.converter` from com.snowflake.kafka.connector.records.SnowflakeAvroConverter to io.confluent.connect.avro.AvroConverter.

2. Make sure your Snowflake connector version >= 1.4.2

@drobert  FYI the code you commented on is only triggered when non-snowflake-converters are used. If you see further problem after changing to confluent's converter, we can look deeper on the lines that you commented on. Previously if you are using SnowflakeAvroConverter, the conversion from AVRO to JSON happens here: https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/records/SnowflakeAvroConverter.java#L175

**Comment by jakemack** [comment]
I am having the same issue. I am using version 2.2.0 of snowflake-kafka-connector. Here is my config with details redacted:

```
connector.class=com.snowflake.kafka.connector.SnowflakeSinkConnector
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=com.snowflake.kafka.connector.records.SnowflakeJsonConverter
snowflake.database.name=<db>
snowflake.schema.name=<schema>
snowflake.topic2table.map=<custom_mapping>
snowflake.private.key.passphrase=<passphrase>
tasks.max=30
topics=<topics_list>
snowflake.private.key=<key>
snowflake.user.name=<username>
snowflake.url.name=<url>
```

The data in the snowflake table includes the schema but for some reason does not deserialize the fields. I'll provide the relevant fields in the Snowflake table below.

```
{
  "payload": {
    "after": {
      "format_pageheight": "DByWAA==",
      ...
    },
    "before": null,
    "op": "r",
    "source": {
      ...
    },
    "transaction": null,
    "ts_ms": 1708417268440
  },
  "schema": {
    "fields": [
      {
        "field": "after",
        "fields": [
          {
            "field": "format_pageheight",
            "name": "org.apache.kafka.connect.data.Decimal",
            "optional": true,
            "parameters": {
              "connect.decimal.precision": "19",
              "scale": "6"
            },
            "type": "bytes",
            "version": 1
          },
          ...
        ],
        "name": "....Value",
        "optional": true,
        "type": "struct"
      },
      ...
    ],
    "name": "....Envelope",
    "optional": false,
    "type": "struct",
    "version": 1
  }
}
```

I was initially using `org.apache.kafka.connect.json.JsonConverter` as the value.converter as well but replication stopped when I hit tombstone records. Switching to `com.snowflake.kafka.connector.SnowflakeSinkConnector` for the value.converter fixed that but now this issue cropped up. I am sidestepping this issue by setting Debezium's connector config property `decimal.handling.mode` to `string` and then converting data back to decimal later in our pipeline.
