### ISSUE TITLE
Allow ingest on an interval in addition to current methods

### ISSUE THREAD

**Issue by yarmiganosca** [snowflakedb/snowflake-kafka-connector#13]
To ensure data on low-throughput topics gets written to Snowflake in a timely manner, it would be great if the connector could be configured to ingest messages into Snowflake every N seconds in addition to the current approaches of record count and total record size (in bytes).

**Comment by binglihub** [comment]
Thank you for your suggestion.
We added a new parameter "buffer.flush.time", and periodically flush cache buffer according to this setting. 
This change will be include in next Connector release (version 0.4.0)

d6b87a0ddb57e9fb6b755470503ec4cf5c923b13

**Comment by yarmiganosca** [comment]
Cool! Do you have any estimate on when 0.4.0 will be released?
