### ISSUE TITLE
Connector fails with unrecoverable exception (Error Code: 3001)

### ISSUE THREAD

**Issue by cfritzlar** [snowflakedb/snowflake-kafka-connector#132]
Snowflake Kafka Connector fails sporadically with the error message below:
"org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception."
[...]
[SF_KAFKA_CONNECTOR] Exception: Failed to ingest file
[SF_KAFKA_CONNECTOR] Error Code: 3001

For some reason, it sometimes helps to restart tasks / the whole connector but it starts failing again after a few hours or days.
We are using the connector to ingest AVRO formatted messages from several Kafka topics into Snowflake. The versions we are facing the issues with are 1.1.0 and even 1.2.3.

Our configuration looks as follows:
[connector_config.txt](https://github.com/snowflakedb/snowflake-kafka-connector/files/4502159/connector_config.txt)

Log message from the Connect worker:
[log_msg.txt](https://github.com/snowflakedb/snowflake-kafka-connector/files/4502101/log_msg.txt)

**Comment by sfc-gh-bli** [comment]
This issue fixed in v1.2.4, please upgrade the connector.
Thank you
