### ISSUE TITLE
Code doesn't compile with Java 11

### ISSUE THREAD

**Issue by ivanyu** [snowflakedb/snowflake-kafka-connector#155]
After [this change](https://github.com/snowflakedb/snowflake-kafka-connector/commit/78823ac1c1f40a60a0638ae8f45d0d0fefc13cfa#diff-4a2bce282c01146d3026bd78aa7e5fd3R24), the project doesn't compile with Java 11 (8 is fine).

This module `com.sun.corba` was deprecated in Java 9 and [removed](https://openjdk.java.net/jeps/320) in Java 11.

Could you please reconsider using it?

**Comment by sfc-gh-bli** [comment]
@sfc-gh-zli FYI

**Comment by sfc-gh-zli** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/pull/164 this one should fix it

**Comment by ivanyu** [comment]
Yes, #164 looks like it, thanks, I'll close this.
