### ISSUE TITLE
Connector fails when insertFiles(..) method is invoked with empty set

### ISSUE THREAD

**Issue by MThomassen** [snowflakedb/snowflake-kafka-connector#167]
In `SnowflakeSinkServiceV1::recoverFileStatues` [loadHistory HTTP method](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-rest-apis.html#endpoint-loadhistoryscan) is invoked and subsequently, a list of to be submitted files in the [insertFiles HTTP method](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-rest-apis.html#endpoint-insertfiles).

This list of files (`filesForIngestion`) could be empty, resulting in an error and irrecoverable Connector Task crash.

HTTP capture:
[failure-http-stream-cleaned.log](https://github.com/snowflakedb/snowflake-kafka-connector/files/4738800/failure-http-stream-cleaned.log)

**Comment by sfc-gh-zli** [comment]
Fixed in https://github.com/snowflakedb/snowflake-kafka-connector/pull/152
