### ISSUE TITLE
Is it possible to directly parse JSON fields into a table? 

### ISSUE THREAD

**Issue by axk7812** [snowflakedb/snowflake-kafka-connector#179]
I am loading the data into snowflake but it's coming as a table with 2 columns:

`RECORD_METADATA | RECORD_CONTENT`

Is it possible to directly map the values -> columns in snowflake without writing a scheduled job to parse the json?

**Comment by sfc-gh-zli** [comment]
Currently that is not supported.

**Comment by axk7812** [comment]
cool thanks for the response

**Comment by prabodhm** [comment]
Any plans on enabling this capability?

**Comment by omrikurtz** [comment]
Commenting here for visibility and for showing interest.
This is a much needed feature as we have to put a lot of money on Snowflake queries otherwise.

Maybe something like allowing a json-schema in the config for specifying the JSON keys to extract?

**Comment by sfc-gh-xhuang** [comment]
This is supported in our Kafka Connector with ingestion.method set to Snowpipe Streaming:
https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka

Currently the schema detection and evolution support in in Private Preview but will go out to public preview soon.
If you wish to have it enabled for your account, please reach out to me or Snowflake support with your account name and deployment.
