### ISSUE TITLE
com.snowflake:base is not resolvable via maven

### ISSUE THREAD

**Issue by kmclarnon** [snowflakedb/snowflake-kafka-connector#181]
It appears from version 1.3.1, the pom of this project was updated to have a parent pom, `com.snowflake:base`, however it appears that artifact was never published, resulting in dependency resolution failures for versions 1.3.1 onwards of `com.snowflak:snowflake-kafka-connector`.

Relevant links: 
- [com.snowflake:snowflake-kafka-connector:1.3.1](https://search.maven.org/artifact/com.snowflake/snowflake-kafka-connector/1.3.1/jar)
- [com.snowflake:base](https://search.maven.org/search?q=g:com.snowflake%20AND%20a:base)

**Comment by sfc-gh-zli** [comment]
Thanks for bring this up, this should be fixed by this: https://github.com/snowflakedb/snowflake-kafka-connector/pull/183
