### ISSUE TITLE
Task Failed - Error Code: 3001 Message: HTTP Status: 429

### ISSUE THREAD

**Issue by JonathanWix** [snowflakedb/snowflake-kafka-connector#189]
Sink Connector Task Failed when snowflake returns HTTP Status: 429 
ErrorBody: Error 429 Too many requests

**Comment by sfc-gh-zli** [comment]
That's because your connector is trying to put too many files to Snowflake. Try to increase buffer.flush.time or reduce your topic and connector number.

**Comment by JonathanWix** [comment]
Thank you for your response. 
Shouldn't the connector handle this throttling error with some backoff instead of stopping the transfer altogether?

**Comment by sfc-gh-zli** [comment]
We have backoff since version 1.4.0. That error happens only after the connector tries and fails for 4 times.

**Comment by JonathanWix** [comment]
Thank you, closing the issue
