### ISSUE TITLE
Connector could have an option to flatten JSON events before storing in snowflake tables

### ISSUE THREAD

**Issue by kkiran13** [snowflakedb/snowflake-kafka-connector#192]
Currently, connector creates snowflake tables (raw events tables) with columns `RECORD_METADATA` and `RECORD_CONTENT`.
We end up creating views to flatten records in `record_content`. Performance of querying views is impacted as volume of events increases. It would be great if the connector has an option to flatten events so that the table created by the connector has all the columns present as keys in event JSON.

**Comment by sfc-gh-zli** [comment]
Please contact Snowflake support to submit feature request.

**Comment by scottredding** [comment]
You could use streams and tasks off of the raw table to flatten the raw events into a table VS using views on top of the raw events table. I would consider this best practice to store both the raw data and the flattened data in Snowflake. If you move towards flattening before loading you lose a lot of the benefits of ELT vs ETL and being able to do schema on-read.
Create a stream on the raw events table then a task that has the view SQL to read from the stream and and execute WHEN SYSTEM$STREAM_HAS_DATA
