### ISSUE TITLE
Uncaught Throwable will take down cleaner thread

### ISSUE THREAD

**Issue by deweyjose** [snowflakedb/snowflake-kafka-connector#194]
https://github.com/snowflakedb/snowflake-kafka-connector/blob/56a71298846d4dbcb663c256d60c19f231014bd6/src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java#L367

It looks possible to throw RuntimeExceptions out of checkStatus, which are not caught within runnable body passed to the executor. 

There is potential to throw RuntimeExceptions from these methods, which could be called from checkStatus.
SnowflakeIngestionServiceV1.readIngestReport
SnowflakeConnectionServiceV2.removeFile 

We observe a situation where there are no "purge stage" messages for various stages in the KConnect logs. We observe the counts of files in the stage those stages to grow unbounded. Once the set of files is large enough we can no longer restart our Kafka Connect Cluster as max.poll.interval.ms thresholds are breached in the consumer, and a never ending cycle of rebalancing occurs. The only workaround is to manually delete the old files in the stages, and setup monitoring etc to detect.

**Comment by deweyjose** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/pull/195

**Comment by sfc-gh-zli** [comment]
Thanks a lot for the issue and the PR, we have a fix that is checked in. https://github.com/snowflakedb/snowflake-kafka-connector/pull/197
