### ISSUE TITLE
Cleaner encountered an exception - Snowflake Connector 1.5.0

### ISSUE THREAD

**Issue by sabarigk** [snowflakedb/snowflake-kafka-connector#259]
We took the 1.5.0 upgrade and seeing the below warning getting popped up in the logs. 

WARN Cleaner encountered an exception class com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:\n]

The log trace doesn't say much on what specifically is failing in the cleaner. What would be the root cause where the cleaner is failing?

**Comment by sfc-gh-zli** [comment]
If it is a continuous failing, please check whether you have the correct permissions on Snowflake objects: https://docs.snowflake.com/en/user-guide/kafka-connector-install.html#required-privileges
