### ISSUE TITLE
Log level setting

### ISSUE THREAD

**Issue by kkiran13** [snowflakedb/snowflake-kafka-connector#263]
Is there a way to set log levels for snowflake connectors? We use snowflake connector in a docker container which is based from confluents connect image.
I've set connect log levels to WARN/ERROR as described here: https://docs.confluent.io/3.1.1/cp-docker-images/docs/operations/logging.html but still continue seeing INFO level logs which looks like below:
```
[task-thread-SnowflakeSinkConnectorTopOfFunnelFlowStepLoaded-0] INFO net.snowflake.ingest.SimpleIngestManager - Attempting to unmarshall insert response - HttpResponseProxy{HTTP/1.1 200 OK [Content-Type: application/json, Date: Thu, 03 Dec 2020 18:30:12 GMT, Expect-CT: enforce, max-age=3600, Strict-Transport-Security: max-age=31536000, Vary: Accept-Encoding, User-Agent, X-Content-Type-Options: nosniff, X-Frame-Options: deny, X-XSS-Protection: : 1; mode=block, Content-Length: 88, Connection: keep-alive] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 88,Chunked: false]}}
[task-thread-SnowflakeSinkConnectorTopOfFunnelFlowStepLoaded-0] INFO net.snowflake.ingest.SimpleIngestManager - Sending Request UUID - 
```
I'm guessing these are from snowflake connectors, so wanted to know if there is some environment variable or setting that can produce only WARN or ERROR messages only?

**Comment by sfc-gh-rcheng** [comment]
If you are using docker, you can add `com.snowflake=DEBUG` to the `CONNECT_LOG4J_LOGGERS` property.

Ex:
`CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR,com.snowflake=DEBUG
`

Closing out issue due to age of issue - please reopen if this is still a concern
