### ISSUE TITLE
When will 1.5.1 be released to Confluent Hub ? 

### ISSUE THREAD

**Issue by carlioth** [snowflakedb/snowflake-kafka-connector#265]
When will 1.5.1 be released to Confluent Hub ? 
They are still at 1.5.0
https://www.confluent.io/hub/snowflakeinc/snowflake-kafka-connector

**Comment by rvertigo** [comment]
Yes! Please someone click the button to publish this to Confluent hub.
```
$ confluent-hub install snowflakeinc/snowflake-kafka-connector:1.5.1

Unable to find a component 
 
Error: Component not found, specify either valid name from Confluent Hub in format: <owner>/<name>:<version:latest> or path to a local file 
```

**Comment by rvertigo** [comment]
@carlioth I filed a ticket with Confluent Support and the Snowflake Connector is available in the Confluent Hub now.
