### ISSUE TITLE
Clarification of Confluent 6.x support

### ISSUE THREAD

**Issue by li-il-li** [snowflakedb/snowflake-kafka-connector#281]
Is Confluent 6.x supported?

The official documentation does not list support for Confluent 6.x in its [prerequisites](https://docs.snowflake.com/en/user-guide/kafka-connector-install.html#installation-prerequisites). Checking release notes and other issues hint that support exists.

Thanks for clarification.

**Comment by sfc-gh-japatel** [comment]
Working on updating tests and documentation.

**Comment by sfc-gh-rcheng** [comment]
Closing this issue out due to age - please reopen if further discussion is needed.
