### ISSUE TITLE
Timeline for getting the connector on Confluent Hub?

### ISSUE THREAD

**Issue by yarmiganosca** [snowflakedb/snowflake-kafka-connector#30]
It's my understanding that uploading Connectors to Confluent Hub isn't as easy as uploading a jar to a package repository, but it would be nice to know what your timeline for getting this Connector onto Confluent Hub is. Are you waiting for 1.0? Is there some approval process that's in the works but not yet complete? Thanks!

**Comment by ikunen-sf** [comment]
Just an update: we are working w/ the Confluent team on this. Stay tuned.

**Comment by binglihub** [comment]
It is available on confluent hub now. 
https://www.confluent.io/hub/snowflake/snowflake-kafka-connector
