### ISSUE TITLE
Need to add support for Plain snowflake UserName and Password

### ISSUE THREAD

**Issue by sql-dr-watson** [snowflakedb/snowflake-kafka-connector#319]
The current implementation of this connector does not allow for use of standard UserName and Password.  This is not easily updatable for key rotation and stops the adoption of the go-snowflake dynamic credential generation from HashiCorp Vault.

Logic could be:
if PrivateKey != null and PrivateKeyPassphrase != null
 -> prop.privateKey & prop.privateKeyPassphrase = input 
else if password != null
-> prop.password = input
else
-> error!

**Comment by sql-dr-watson** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/pull/320

**Comment by sfc-gh-japatel** [comment]
Feel free to open. Commented on the #320
