### ISSUE TITLE
Allow configurable separator topic and table for snowflake.topic2table.map parameter

### ISSUE THREAD

**Issue by dlg99** [snowflakedb/snowflake-kafka-connector#337]
The context:
I packaged Snowflake connector with Kafka Connect Adaptor for Apache Pulsar to use it as a sink for Pulsar (it works! except this one parameter so far).

Currently `snowflake.topic2table.map` expects `topic:table[,topic:table]` format, this does not handle Pulsar's topic URLs `persistent://tenant/namespace/topic-name.

Having configurable separator instead of `:` should be enough.

**Comment by sfc-gh-rcheng** [comment]
Closing this issue out due to age - please reopen if further discussion is needed.
