### ISSUE TITLE
snowflake-kaka-connector not able to decrypt private key 

### ISSUE THREAD

**Issue by harinjy** [snowflakedb/snowflake-kafka-connector#341]
I am getting the below error using snowflake-kafka connector docker image
`[2021-10-05 16:46:40,553] ERROR Validate: Error connecting to snowflake:
[SF_KAFKA_CONNECTOR] Exception: Invalid encrypted private key or passphrase
[SF_KAFKA_CONNECTOR] Error Code: 0018
[SF_KAFKA_CONNECTOR] Detail: failed to decrypt private key. Please verify input private key and passphrase. Snowflake Kafka Connector only supports encryption algorithms in FIPS 140-2
[SF_KAFKA_CONNECTOR] Message: unable to decode base64 string: invalid characters encountered in base64 data
[SF_KAFKA_CONNECTOR] org.bouncycastle.util.encoders.Base64.decode(Unknown Source)
[SF_KAFKA_CONNECTOR] org.bouncycastle.util.io.pem.PemReader.loadObject(Unknown Source)
[SF_KAFKA_CONNECTOR] org.bouncycastle.util.io.pem.PemReader.readPemObject(Unknown Source)
[SF_KAFKA_CONNECTOR] org.bouncycastle.openssl.PEMParser.readObject(PEMParser.java:92)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.EncryptionUtils.parseEncryptedPrivateKey(EncryptionUtils.java:34)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.InternalUtils.createProperties(InternalUtils.java:152)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceFactory$SnowflakeConnectionServiceBuilder.setProperties(SnowflakeConnectionServiceFactory.java:58)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.SnowflakeSinkConnector.validate(SnowflakeSinkConnector.java:234)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:400)
[SF_KAFKA_CONNECTOR] org.apache.kafka.connect.runtime.AbstractHerder.lambda$validateConnectorConfig$2(AbstractHerder.java:351)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[SF_KAFKA_CONNECTOR] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[SF_KAFKA_CONNECTOR] java.base/java.lang.Thread.run(Thread.java:829), errorCode:0018 (com.snowflake.kafka.connector.SnowflakeSinkConnector)`

My docker file:

```
FROM confluentinc/cp-kafka-connect
RUN mkdir -p /usr/share/java/kafka-connect-snowflake
COPY --chmod=0777 snowflakeinc-snowflake-kafka-connector-1.5.5/* /usr/share/java/kafka/
COPY --chmod=0777 rsa_key.p8 /home/appuser

```

I got the connector plugin from [here](https://www.confluent.io/hub/snowflakeinc/snowflake-kafka-connector).

My Connector configuration:

```
name=SnowflakeSinkConnector
connector.class=com.snowflake.kafka.connector.SnowflakeSinkConnector
topics=sftest
tasks.max=1
snowflake.url.name=xxxxxx.us-east-1.snowflakecomputing.com:443
snowflake.user.name=xxxx
snowflake.database.name=xxxx
snowflake.schema.name=XXXX
snowflake.private.key=/home/appuser/rsa_key.p8
snowflake.private.key.passphrase=xxxxxx
```

Key was generated using:
`openssl genrsa 2048 | openssl pkcs8 -topk8 -v2 aes256 -inform PEM -out rsa_key.p8`
I am able to succesfuly connect to snowflake using SnowSQL command with the same key, but not through connector.
Appreciate any help!

**Comment by sfc-gh-japatel** [comment]
For encrypted private key, you would need fips libraries in your `share/java/kafka` path

https://docs.snowflake.com/en/user-guide/kafka-connector-install.html#download-the-kafka-connector-files
