### ISSUE TITLE
Option to enable CHANGE_TRACKING on automatically created tables

### ISSUE THREAD

**Issue by mrjoycee** [snowflakedb/snowflake-kafka-connector#343]
I would like to attach a stream to tables created and owned by the Kafka connector. Doing this requires change tracking to be enabled on the table, however our security model makes enabling this difficult as we would have to allow users to assume the role that is being used by the Kafka connector. It would be great if there was a configurable option in the connector for creating tables with change tracking enabled.

**Comment by sfc-gh-mwies** [comment]
@sfc-gh-japatel Do you have any thoughts on this?

**Comment by adriank-convoy** [comment]
We're finally moving from an S3 connector + lambda that creates snow pipes to the official Snowflake connector, and would also find this useful. We're going to have to add some custom code/security configuration to get this enabled on tables created by the connector, it would be great if it could just optionally do it for us

**Comment by sfc-gh-japatel** [comment]
Yes, this should be possible to do it.

**Comment by mrjoycee** [comment]
@sfc-gh-japatel If you're open to community contributions I've got the code for this working in a fork. We've been using it in production for a while now.

**Comment by sfc-gh-japatel** [comment]
Hey yes sure, that would be awesome! Can you open the PR in this repo? For first time contributors, you will have to sign CLA which I can ask our legal department to send to an email address. 

Thanks in advance!

**Comment by convoy-lb** [comment]
> @sfc-gh-japatel If you're open to community contributions I've got the code for this working in a fork. We've been using it in production for a while now.

@mrjoycee - Is there an open PR for the proposed contribution? We're currently leveraging a custom procedure and task to accomplish this and would rather not have that additional overhead if we can avoid it : ).

**Comment by sfc-gh-rcheng** [comment]
Closing this issue out due to age - please reopen if @mrjoycee has a PR or if further discussion is needed.

**Comment by sfc-gh-japatel** [comment]
FYI, we will soon have an option to enable change tracking in your landing table. Stay tuned!

**Comment by sfc-gh-japatel** [comment]
@convoy-lb @mrjoycee feel free to open a PR and we will take a look, FYI, we would want to have it behind a parameter and not enabled by default for all tables.
