### ISSUE TITLE
Implement the topics.regex configuration parameter

### ISSUE THREAD

**Issue by yarmiganosca** [snowflakedb/snowflake-kafka-connector#35]
Kafka Connect's docs indicate there's a [topics.regex configuration parameter](https://docs.confluent.io/current/installation/configuration/connect/sink-connect-configs.html) that's provided by the `SinkTask` class, which your SinkTask class extends. It would be really useful to us to have that configuration parameter honored by the Snowflake Connector. It would let us add Kafka topics that met a certain pattern without having to update our Connector configuration.

**Comment by ikunen-sf** [comment]
Thanks for the suggestion -- we are looking at this.

A question, though. Without an entry in the tables2topicsmap, we ingest topics into a table with the same name. This can cause problems with Snowflake's limitations on table names. E.g., we can't have a table with a hyphen, so we need to remap "my-topic" to something. But we can't extend the map to dynamically-added topics.

What would you prefer:
1. We don't ingest new topics whose names are invalid Snowflake identifiers.
2. We strip any non-conforming characters, and append a disambiguator to the name. E.g., "foo-bar" might become "foobar_12349876".

**Comment by yarmiganosca** [comment]
I think as long as you logged that the attempt had been made, with the offending topic name, and the logs weren't flooded with that (so like no more than once every five seconds per offending topic plz plz), we can handle that on our end. We're controlling topic names with a ruby gem that handles Avro schema encoding and publishing to a topic, so we're already abiding by the Snowflake table name rules, but I think logging is at least a good first step for a good general failure behavior.

**Comment by iexos** [comment]
We auto-generate the table name in the map anyway. The corresponding part in the shell script is:
```
table=$(echo $topic | tr '.[:lower:]' '_[:upper:]')
```
This works pretty well for us, as we only have dots as special characters in topic names. In my view the second option is preferred, as our team is just one of many users of Kafka and cannot control the naming convention just for this connector.

**Comment by binglihub** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/commit/4db875984b38f55b78a1f90186129f6213cc318e
