### ISSUE TITLE
Snowflake Kafka Connector. Getting Duplicates 

### ISSUE THREAD

**Issue by RamakrishnaKonda-111** [snowflakedb/snowflake-kafka-connector#354]
I have a 3 node cluster with 3 different virtual machines(VM). How can we restrict duplicates as its even in the single server as well as the cluster environment. Please guide. As I am getting duplicates even in the single as well as dual node cluster. As the partition of the data consumption is 5. So these 5 partitions are being used to pump the data. If as you said above if we take only tasks.max=1 then how the parallelism can be achieved and the throughput performance will be achieved. This is same even one node and when even with multiple node. Please help

**Comment by sfc-gh-japatel** [comment]
Hello @RamakrishnaKonda-111 we are working on Exactly once for our KC. Please stay tuned for next versions. It will be in a preview mode where you can try it out. 

Also you can keep task.max = no of partitions. 

And duplicates right now happen in rebalance situations. 

CC: @sfc-gh-anwang

**Comment by sfc-gh-japatel** [comment]
FYI, you can try version 1.7.1 which has exactly once. But is still in private preview mode.
