### ISSUE TITLE
1:1 mapping between pipes and topic partitions potentially leads to high costs

### ISSUE THREAD

**Issue by anekdoti** [snowflakedb/snowflake-kafka-connector#363]
In the current implementation, the tasks of the Snowflake Kafka connector create a Snowflake pipe for each partition of the consumed Kafka topic. 

Especially in the face of large amounts of long-term historical data, a Kafka topic often has a large number of partitions in order to consume the historical data in an acceptable time frame. For processing of new events, often a much smaller degree of parallelism or none at all would be sufficient. However, the number of partitions of a Kafka topic can not be easily changed and thus is normally oriented on the maximum degree of parallelism required.

To still be able to choose a different scaling in the ingestion of a Kafka topic, independent of the number of partitions, it would be desirable to either have the number of pipes be tied to the number of tasks, or to be able to choose a number of pipes such that #tasks <= #pipes <= #partitions, or similar. This way, historical data could be consumed with a large number of parallel pipes while for processing of life events this could be tuned down to a smaller number of parallel pipes, reducing the costs of a long-running ingestion pipeline.

By a look at the implementation of the Snowflake Kafka connector, I admit that this would need a certain amount of refactoring, but I also do not see an obvious reason in the architecture to not consume a number of partitions into the same pipe.

Any insights, opinions and ideas would be very welcome!

**Comment by malthe** [comment]
I suppose this is obviated by Snowpipe Streaming where there's no pipe object.

**Comment by sfc-gh-rcheng** [comment]
Yup Streaming solves a lot of this, closing this issue out due to age - please reopen if further discussion is needed.

**Comment by anekdoti** [comment]
It is true that the Streaming API solves this problem and it is overall a huge improvement. Unfortunately, we can not use it as it does not support the custom SnowflakeAvroConverter and in particular its feature to provide a reader schema.
