### ISSUE TITLE
Staging file access and privileges with error insuffucient previleges even after necessary access given

### ISSUE THREAD

**Issue by AustinJackson-GitHub** [snowflakedb/snowflake-kafka-connector#367]
[2021-12-17 00:44:51,722] INFO Final History URIBuilder - https://XXXX.XXX-1.snowflakecomputing.com:443/v1/data/pipes/KAFKA_DB.KAFKA_SCHEMA.SNOWFLAKE_KAFKA_CONNECTOR_file_stream_demo_distributed_1770328299_PIPE_UAT_PRODUCT_TOPIC_15DEC2021_3/insertReport?requestId=03f9355d-4874-44ad-a8c0-b1bcfc1c9a7c&beginMark=7_4529 (net.snowflake.ingest.connection.RequestBuilder:384)
[2021-12-17 00:44:51,858] INFO In retryRequest for service unavailability with statusCode:200 and uri:/v1/data/pipes/KAFKA_DB.KAFKA_SCHEMA.SNOWFLAKE_KAFKA_CONNECTOR_file_stream_demo_distributed_1770328299_PIPE_UAT_PRODUCT_TOPIC_15DEC2021_3/insertReport?requestId=03f9355d-4874-44ad-a8c0-b1bcfc1c9a7c&beginMark=7_4529 (net.snowflake.ingest.utils.HttpUtil:118)
[2021-12-17 00:44:51,858] INFO Attempting to unmarshall history response - HttpResponseProxy{HTTP/1.1 200 OK [Content-Type: application/json, Date: Fri, 17 Dec 2021 00:44:51 GMT, Expect-CT: enforce, max-age=3600, Strict-Transport-Security: max-age=31536000, Vary: Accept-Encoding, User-Agent, X-Content-Type-Options: nosniff, X-Country: United States, X-Frame-Options: deny, X-XSS-Protection: : 1; mode=block, Connection: keep-alive] net.snowflake.ingest.internal.apache.http.client.entity.DecompressingEntity@38673c33} (net.snowflake.ingest.SimpleIngestManager:592)
[2021-12-17 00:44:51,858] INFO 
[SF_KAFKA_CONNECTOR] searched 52 files in ingest report, found 1 (com.snowflake.kafka.connector.internal.SnowflakeIngestionServiceV1:63)
[2021-12-17 00:44:52,004] INFO 
[SF_KAFKA_CONNECTOR] purge 1 files from stage: SNOWFLAKE_KAFKA_CONNECTOR_file_stream_demo_distributed_1770328299_STAGE_UAT_PRODUCT_TOPIC_15DEC2021 (com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1:63)
[2021-12-17 00:44:52,358] WARN Cleaner encountered an exception class com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:

[SF_KAFKA_CONNECTOR] **Exception: Failed to upload file**
[SF_KAFKA_CONNECTOR] Error Code: 2003
[SF_KAFKA_CONNECTOR] Detail: Failed to upload file to Snowflake Stage though JDBC
[SF_KAFKA_CONNECTOR] Message: SQL access control error:
[SF_KAFKA_CONNECTOR] **Insufficient privileges to operate on table stage 'UAT_PRODUCT_TOPIC_15DEC2021'**
[SF_KAFKA_CONNECTOR] net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:126)
[SF_KAFKA_CONNECTOR] net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:66)
[SF_KAFKA_CONNECTOR] net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:434)
[SF_KAFKA_CONNECTOR] net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:338)
[SF_KAFKA_CONNECTOR] net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:482)
[SF_KAFKA_CONNECTOR] net.snowflake.client.jdbc.SnowflakeFileTransferAgent.parseCommandInGS(SnowflakeFileTransferAgent.java:1180)
[SF_KAFKA_CONNECTOR] net.snowflake.client.jdbc.SnowflakeFileTransferAgent.parseCommand(SnowflakeFileTransferAgent.java:843)
[SF_KAFKA_CONNECTOR] net.snowflake.client.jdbc.SnowflakeFileTransferAgent.<init>(SnowflakeFileTransferAgent.java:819)
[SF_KAFKA_CONNECTOR] net.snowflake.client.jdbc.DefaultSFConnectionHandler.getFileTransferAgent(DefaultSFConnectionHandler.java:187)
[SF_KAFKA_CONNECTOR] net.snowflake.client.jdbc.SnowflakeConnectionV1.uploadStreamInternal(SnowflakeConnectionV1.java:867)
[SF_KAFKA_CONNECTOR] net.snowflake.client.jdbc.SnowflakeConnectionV1.uploadStream(SnowflakeConnectionV1.java:772)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1.moveToTableStage(SnowflakeConnectionServiceV1.java:509)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.moveToTableStage(SnowflakeSinkServiceV1.java:884)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.checkStatus(SnowflakeSinkServiceV1.java:823)
[SF_KAFKA_CONNECTOR] com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.lambda$startCleaner$0(SnowflakeSinkServiceV1.java:478)
[SF_KAFKA_CONNECTOR] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[SF_KAFKA_CONNECTOR] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[SF_KAFKA_CONNECTOR] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[SF_KAFKA_CONNECTOR] java.lang.Thread.run(Thread.java:748)
[com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:284), com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:266), com.snowflake.kafka.connector.internal.SnowflakeErrors.getException(SnowflakeErrors.java:256), com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1.moveToTableStage(SnowflakeConnectionServiceV1.java:516), com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.moveToTableStage(SnowflakeSinkServiceV1.java:884), com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.checkStatus(SnowflakeSinkServiceV1.java:823), com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1$ServiceContext.lambda$startCleaner$0(SnowflakeSinkServiceV1.java:478), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)] (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1:81)
[2021-12-17 00:44:54,211] INFO 
[SF_KAFKA_CONNECTOR] uploadWithoutConnection successful for stageName:SNOWFLAKE_KAFKA_CONNECTOR_file_stream_demo_distributed_1770328299_STAGE_UAT_PRODUCT_TOPIC_15DEC2021, filePath:file_stream_demo_distributed_1770328299/UAT_PRODUCT_TOPIC_15DEC2021/5/2934937_2935294_1639701894001.json.gz (com.snowflake.kafka.connector.internal.SnowflakeInternalStage:63)
[2021-12-17 00:44:54,211] INFO 
[SF_KAFKA_CONNECTOR] pipe SNOWFLAKE_KAFKA_CONNECTOR_file_stream_demo_distributed_1770328299_PIPE_UAT_PRODUCT_TOPIC_15DEC2021_5, flush pipe: file_stream_demo_distributed_1770328299/UAT_PRODUCT_TOPIC_15DEC2021/5/2934937_2935294_1639701894001.json.gz (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1:63)
[2021-12-17 00:44:54,456] INFO 

**[SF_KAFKA_CONNECTOR] uploadWithoutConnection successful for stageName:SNOWFLAKE_KAFKA_CONNECTOR_file_stream_demo_distributed_1770328299_STAGE_UAT_PRODUCT_TOPIC_15DEC2021, filePath:file_stream_demo_distributed_1770328299/UAT_PRODUCT_TOPIC_15DEC2021/4/2948067_2948377_1639701793509.json.gz (com.snowflake.kafka.connector.internal.SnowflakeInternalStage:63)
[2021-12-17 00:43:13,759] INFO 
[SF_KAFKA_CONNECTOR] pipe SNOWFLAKE_KAFKA_CONNECTOR_file_stream_demo_distributed_1770328299_PIPE_UAT_PRODUCT_TOPIC_15DEC2021_4, flush pipe: file_stream_demo_distributed_1770328299/UAT_PRODUCT_TOPIC_15DEC2021/4/2948067_2948377_1639701793509.json.gz (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1:63)**

However, these were also given as the table was created manually "KAFKA_DB"."KAFKA_SCHEMA"."**UAT_PRODUCT_TOPIC_15DEC2021**"

GRANT READ,WRITE ON FUTURE STAGES IN SCHEMA "KAFKA_DB"."KAFKA_SCHEMA" TO ROLE "KAFKA_CONNECTOR_ROLE_1";

GRANT WRITE ON STAGE "KAFKA_DB"."KAFKA_SCHEMA"."SNOWFLAKE_KAFKA_CONNECTOR_FILE_STREAM_DEMO_DISTRIBUTED_1770328299_STAGE_UAT_PRODUCT_TOPIC_15DEC2021" TO ROLE "KAFKA_CONNECTOR_ROLE_1";

grant usage on database kafka_db to role kafka_connector_role_1;
grant usage on schema kafka_schema to role kafka_connector_role_1;
grant create table on schema kafka_schema to role kafka_connector_role_1;
grant create stage on schema kafka_schema to role kafka_connector_role_1;
grant create pipe on schema kafka_schema to role kafka_connector_role_1;

GRANT READ on stage "KAFKA_DB"."KAFKA_SCHEMA"."SNOWFLAKE_KAFKA_CONNECTOR_FILE_STREAM_DEMO_DISTRIBUTED_1770328299_STAGE_UAT_PRODUCT_TOPIC_15DEC2021" to role kafka_connector_role_1;

GRANT WRITE on stage "KAFKA_DB"."KAFKA_SCHEMA"."SNOWFLAKE_KAFKA_CONNECTOR_FILE_STREAM_DEMO_DISTRIBUTED_1770328299_STAGE_UAT_PRODUCT_TOPIC_15DEC2021" to role kafka_connector_role_1;

But still even after these rights getting the error. 

Please help and guide

**Comment by shaunmaris** [comment]
Hi there, we are also receiving these permission errors. Would be great to understand the issue and perhaps get a fix in place.

![image](https://user-images.githubusercontent.com/47876226/175190704-0fe3a284-05df-4ad2-b274-15a729d70934.png)

**Comment by sfc-gh-rcheng** [comment]
Closing this issue out due to age - please reopen if further discussion is needed.
