### ISSUE TITLE
Where is Broken Input going

### ISSUE THREAD

**Issue by madisoncoder15** [snowflakedb/snowflake-kafka-connector#38]
![image](https://user-images.githubusercontent.com/47506924/64878863-1f0dc280-d61a-11e9-953e-7e6067753414.png)

As per the 0.4.0 release, the connector can handle invalid message types (not sure if it can handle nulls still), but I don't know where these invalid messages are being sent. What does 'table stage' mean as mentioned in the release?

Invalid messages aren't showing up in the internal stage when I send them and I don't see any additional tables/stages/topics being created in snowflake to handle the invalid messages.

**Comment by ikunen-sf** [comment]
We need to look into the null issue, but the design is to move all problematic data to the table stage for the target table. You can read more about table stages [here](https://docs.snowflake.net/manuals/user-guide/data-load-local-file-system-create-stage.html#table-stages), but the short of it is that each table has an associated stage named "@%mytable".

**Comment by madisoncoder15** [comment]
I found the mentioned table stage where the faulty messages are going, but it appears that the message contents is showing up under the record_metadata rather than the record_content, and the actual record_metadata is missing. I was required to create a file format with the error_on_column_count_mismatch configuration set to false in order to display the table stage.

![image](https://user-images.githubusercontent.com/47506924/65167185-ae92e700-da07-11e9-9e25-673401b16e69.png)

**Comment by binglihub** [comment]
The file content on table stage is what connector received from Kafka. Since it is invalid (not a JSON or Avro), Connector can't process. So connector directly write it into a file and save on table stage

**Comment by yarmiganosca** [comment]
Is there any way to hook into the standard Connector failure handling behavior and send "bad" messages to a dead-letter topic?

**Comment by sfc-gh-zli** [comment]
This https://github.com/snowflakedb/snowflake-kafka-connector/pull/171 PR would enable the connector to support non-snowflake converters. If you use native json/avro converters, DLQ is naturally supported.
