### ISSUE TITLE
Updates not being reflected in snowflake tables

### ISSUE THREAD

**Issue by LauroSilva1** [snowflakedb/snowflake-kafka-connector#387]
We are currently using this connector alongside a Debezium source connector to do Change Data Capture, but while Debezium captures the Inserts, Updates and Deletes in the Kafka topic, those are not reflected in our target table in Snowflake, only the Inserts, is this a limitation of snowflake, the connector or do i have something configured wrong?

**Comment by sfc-gh-japatel** [comment]
Hey @LauroSilva1 I dont think SF connector filters inserts from updates and deletes. If they are new offsets in the topic, it should be present in SF table.

**Comment by LauroSilva1** [comment]
Hey @sfc-gh-japatel thanks for the prompt response, is this on the roadmap as a feature? or is it not possible because on how snowflake works?

**Comment by sfc-gh-japatel** [comment]
Hey sorry @LauroSilva1 I kind of understand what Debezium produces (CDC) but a little confused on why it is not visible on SF side. If there are records from debezium pulled into sf (since it is source connector) it should be available on snowflake side. It is possible we wont distinguish them but it should be present in Snowflake.. 

What am I missing? can you give an example?

**Comment by LauroSilva1** [comment]
so this connector doesn't filter between updates and deletes, but i should pick them if they are new offsets? after reading that i came back to check my kafka pipelines and it seems my connector is not generating new offsets on updates, which is probably why im not seeing them in snowflake, im currently debugging all my pipeline, i'll come back here with an update if my issue is related to this connector or not, thank you for your time @sfc-gh-japatel

**Comment by sfc-gh-japatel** [comment]
> so this connector doesn't filter between updates and deletes, but i should pick them if they are new offsets?
Correct!

**Comment by LauroSilva1** [comment]
it seems the problem was on my side, it does pick up updates and deletes, it just doesn't differentiate between them, thank you for your time and help @sfc-gh-japatel , i'm closing this issue as it's been solved
