### ISSUE TITLE
Missing Metadata

### ISSUE THREAD

**Issue by madisoncoder15** [snowflakedb/snowflake-kafka-connector#39]
According to the 0.4.0 release, it stated there would be a header, key, timestamp, and Schema ID included in the record_metadata column. Since the 0.3.2 release, I've noticed a timestamp has been added but nothing else. Where are the additional metadata elements (especially the Kafka key)?

![image](https://user-images.githubusercontent.com/47506924/64889699-7f5d2e00-d633-11e9-89c3-a9bbfc36c012.png)

**Comment by ikunen-sf** [comment]
What are you using for the keys in your topic?

**Comment by sabarigk** [comment]
We are passing a string as the key to Kafka. We generate this internally to uniquely identify the message payload.

**Comment by ikunen-sf** [comment]
Got it, thanks. We'll take a look.

**Comment by binglihub** [comment]
fixed missing key issue
https://github.com/snowflakedb/snowflake-kafka-connector/commit/0360d0b316d1d66dc1ab94fc6b7c6199a689310f

tested headers and schema id, both of them work well on my env. Let me know if you still have issue about them.

**Comment by sabarigk** [comment]
Thanks for fixing the issue. I am assuming this will be part of the next release. When is the next release planned?

**Comment by binglihub** [comment]
We released it today, you can check out from Maven later.
