### ISSUE TITLE
Custom Table Schema

### ISSUE THREAD

**Issue by Jacob-Holland-CKO** [snowflakedb/snowflake-kafka-connector#402]
Currently the default behaviour is to create a table if one does not exist & use a default schema defined in the `src\main\java\com\snowflake\kafka\connector\internal\SnowflakeConnectionServiceV1.java` location.

The idea would be to make the default schema configurable so that metadata columns (or anything users want really) could be added in.

E.g. 

```java
  @Override
  public void createTable(final String tableName, final boolean overwrite) {
    checkConnection();
    InternalUtils.assertNotEmpty("tableName", tableName);
    String query;
    if (overwrite) {
      query =
          "create or replace table identifier(?) (record_metadata "
              + "variant, record_content variant)";
    } else {
      query =
          "create table if not exists identifier(?) (record_metadata "
              + "variant, record_content variant)";
    }
    try {
      PreparedStatement stmt = conn.prepareStatement(query);
      stmt.setString(1, tableName);
      stmt.execute();
      stmt.close();
    } catch (SQLException e) {
      throw SnowflakeErrors.ERROR_2007.getException(e);
    }

    logInfo("create table {}", tableName);
  }
```

becomes:

```java
 @Override
  public void createTable(final String tableName, final boolean overwrite, final String query) {
    checkConnection();
    InternalUtils.assertNotEmpty("tableName", tableName);
    try {
      PreparedStatement stmt = conn.prepareStatement(query);
      stmt.setString(1, tableName);
      stmt.execute();
      stmt.close();
    } catch (SQLException e) {
      throw SnowflakeErrors.ERROR_2007.getException(e);
    }

    logInfo("create table {}", tableName);
  }
```

**Comment by sfc-gh-japatel** [comment]
Hi @Jacob-Holland-CKO we will not support custom table format in snowpipe based kafka connector. 
For snowpipe streaming, we have schematization feature recently announced in private preview. For that, we will auto detect the table schema from the schema registry if you records are in avro format.

**Comment by Jacob-Holland-CKO** [comment]
> Hi @Jacob-Holland-CKO we will not support custom table format in snowpipe based kafka connector. For snowpipe streaming, we have schematization feature recently announced in private preview. For that, we will auto detect the table schema from the schema registry if you records are in avro format.

Thanks for this! Saw this release & are going down this route. Will close issue.
