### ISSUE TITLE
Compile error in TestUtils.java pulled from master

### ISSUE THREAD

**Issue by sagarrao12** [snowflakedb/snowflake-kafka-connector#432]
Hi, I pulled the latest from master but there seems to be a problem in compiling due to this line: 
https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/test/java/com/snowflake/kafka/connector/internal/TestUtils.java#L219

`InternalUtils.createProperties` expects 3 arguments but only 2 are being sent. I guess networkTimeout should be set to 0?

**Comment by sfc-gh-tzhang** [comment]
@sagarrao12 This should be fixed now?

**Comment by sfc-gh-tzhang** [comment]
close since no reply, feel free to reopen if needed
