### ISSUE TITLE
SnowflakeSinkServiceV1: log "task is already registered" as info instead of an error

### ISSUE THREAD

**Issue by dlg99** [snowflakedb/snowflake-kafka-connector#441]
As I understand this is perfectly normal ad requires no attention:
https://github.com/snowflakedb/snowflake-kafka-connector/blob/ed1b37a3554be84892e99e165023d0b856ecd24f/src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java#L119-L121

Yet this logged as an error which raises questions/investigation in whether some configuration has to be corrected.
I think the message can be logged as info or warning instead of an error.

**Comment by sfc-gh-rcheng** [comment]
Changed merged, thanks for the suggestion
