### ISSUE TITLE
SnowflakeSinkConnectorConfig: key/value converters misplaced in teh const definitions

### ISSUE THREAD

**Issue by dlg99** [snowflakedb/snowflake-kafka-connector#443]
Should be switched, like `KEY_CONVERTER_CONFIG_FIELD = "key.converter"` otherwise will lead to unexpected problems downstream

https://github.com/snowflakedb/snowflake-kafka-connector/blob/4b90cdeb5695543a3dec6299aa0018b7ed92b423/src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnectorConfig.java#L163-L165

**Comment by sfc-gh-tzhang** [comment]
Fix should be part of 1.8.1
