### ISSUE TITLE
Still getting "Connector name is empty or invalid" with invalid Snowflake identifiers 

### ISSUE THREAD

**Issue by kguelseven** [snowflakedb/snowflake-kafka-connector#456]
Hi folks

I just run into the issue described in #62 with v1.8.0 and checked #115. I think these lines should be swapped for the validation to work with the converted connector name. 

https://github.com/snowflakedb/snowflake-kafka-connector/blob/d4816a598af7e8151406432b4983564757d0b2dc/src/main/java/com/snowflake/kafka/connector/SnowflakeSinkConnector.java#L87-L90

**Comment by sfc-gh-japatel** [comment]
What is the application name you are using? Can you paste the error message?

**Comment by kguelseven** [comment]
The connector is named korhan.snowflake-connector. 

> 2022-07-06 20:18:06,703 ERROR
[SF_KAFKA_CONNECTOR] name is empty or invalid. It should match Snowflake object identifier syntax. Please see the documentation. (com.snowflake.kafka.connector.Utils) [connector-thread-korhan.snowflake-connector]
2022-07-06 20:18:06,703 ERROR WorkerConnector{id=korhan.snowflake-connector} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector) [connector-thread-korhan.snowflake-connector]
com.snowflake.kafka.connector.internal.SnowflakeKafkaConnectorException:
[SF_KAFKA_CONNECTOR] Exception: Invalid input connector configuration
[SF_KAFKA_CONNECTOR] Error Code: 0001
[SF_KAFKA_CONNECTOR] Detail: input kafka connector configuration is null, missing required values, or wrong input value

**Comment by kguelseven** [comment]
Hi @sfc-gh-japatel could you look at my suggestion? The fix seems to be trivial in this case.
