### ISSUE TITLE
Connectors that reads topics with dot in their name does not write any data to snowflake database

### ISSUE THREAD

**Issue by ulfox** [snowflakedb/snowflake-kafka-connector#47]
Below is the configuration

> name=SnowflakeConnector
> connector.class=com.snowflake.kafka.connector.SnowflakeSinkConnector
> snowflake.topic2table.map=devdb.engines:engines
> tasks.max=1
> topics=devdb.engines
> snowflake.url.name=***
> snowflake.database.name=mydb
> snowflake.schema.name=public
> buffer.count.records=10000
> snowflake.user.name=***
> snowflake.private.key=***
> snowflake.user.role=***
> value.converter=com.snowflake.kafka.connector.records.SnowflakeJsonConverter
> key.converter=com.snowflake.kafka.connector.records.SnowflakeJsonConverter
> buffer.size.bytes=5242880

The connector above runs normally without an issue but no data ever appears in the **snowflakedb**

If I copy the data from the above topic to a new topic called **devdb_engines** and update the connector's configuration with the above **topicname**, then data are being written normally in the **snowflakedb**

**Comment by binglihub** [comment]
Please try our new connector (0.5.0), it will automatically replace "." by "_"

**Comment by ulfox** [comment]
Thank you!
