### ISSUE TITLE
Tombstone handling for Json schema data from schema registry

### ISSUE THREAD

**Issue by mounikamuddasani1** [snowflakedb/snowflake-kafka-connector#481]
We are trying to handle tombstones in topic with Jsonschema using schemaregistr. 
When the Kafka connector encounters a tombstone record, it needs to insert an empty JSON string in the record content column in snowflake.

Connector version used: 1.7.0 
When using behavior.on.null.value:DEFAULT, 

it fails with error

message:
[SF_KAFKA_CONNECTOR] Failed to parse JSON record
[SF_KAFKA_CONNECTOR] java.io.CharConversionException: Invalid UTF-32 character 0xa17a2241 (above 0x0010ffff) at char #1, byte #7)
serviceName:kafka-connect

**Comment by mounikamuddasani1** [comment]
Connector config:

{
        "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
        "snowflake.topic2table.map": "TopicName-dev:tablename_dev",
        "topics": "TopicName-dev",
        "tasks.max": "3",
        "snowflake.private.key.passphrase": "${paramstore:snowflake/private.key.passphrase}",
        "buffer.flush.time": "1800",
        "snowflake.url.name": "${paramstore:snowflake/url.name}",
        "snowflake.database.name": "${paramstore:snowflake/database.name}",
        "snowflake.schema.name": "${paramstore:snowflake/schema.name}",
        "value.converter.schema.registry.url": "${paramstore:schemaRegistryUrl}",
        "buffer.count.records": "10000",
        "snowflake.private.key": "${paramstore:snowflake/private.key}",
        "snowflake.user.name": "${paramstore:snowflake/user.name}",
        "name": "Connector_dev",
        "value.converter.schemas.enable": "false",
        "value.converter.break.on.schema.registry.error": "false",
        "value.converter": "com.snowflake.kafka.connector.records.SnowflakeJsonConverter",
        "key.converter":"org.apache.kafka.connect.storage.StringConverter",
        "behavior.on.null.values": "DEFAULT",
        "consumer.override.auto.offset.reset": "latest"
    }

**Comment by sfc-gh-xhuang** [comment]
We recommend using Snowpipe Streaming and version 2.1.0 instead of version 1.7.0
V 1.7.0 is unsupported
