### ISSUE TITLE
Logs showing Sink Task still running while Connector and Task are in 'paused' state

### ISSUE THREAD

**Issue by JonathonO** [snowflakedb/snowflake-kafka-connector#513]
Currently testing:
- Snowflake Sink v1.8.2
- Kafka Connect 3.3.0 (Confluent Platform 7.3.0-ce)

Tested same on previous versions (1.8.1 and 3.2.0) also and get the same behaviour.

After pausing the Sink via Connect REST API and confirming via `/connectors?expand=status` and `/connectors/{connector name}/tasks/{task id}/status` that both the connector and task were paused, the Connector and Task still seems to be running, because connect logs keep showing these messages:
```
Nov 15 14:35:01 dev-kafka-connect-01 connect-distributed[3629]: [2022-11-15 14:35:01,868] INFO [test-conn-sf|task-0] [SF_KAFKA_CONNECTOR] [KC:2086829359|SfTask[ID:0.1, #2]] successfully called precommit with 2 records, execution time: 0 seconds (com.snowflake.kafka.connector.SnowflakeSinkTask:107)
```

Only ways I've found to stop that are:
- Restarting Task after Task and Connector enters Paused state
- Deleting Connector

**Comment by JonathonO** [comment]
Seems there's a large volume of these log messages, even when there's no data to be processed? What would be _precommitted_ if there's no data?

```
INFO [test-conn-sf|task-0] [SF_KAFKA_CONNECTOR] [KC:2086829359|SfTask[ID:0.1, #2]] successfully called precommit with 2 records, execution time: 0 seconds
```

Latest (as of this week) build from master showing same behaviour.

**Comment by sfc-gh-wfateem** [comment]
Hi @JonathonO,

There really shouldn't be a notification telling you that two records were processed if there's no data, but it's kind of difficult for us to really say anything about your issue with this information that you provided on its own.
Can you walk us through how you're testing this and how have you been able to confidently confirm that there weren't any offsets that needed to be committed at the time? 
Can you share the full log with us by any chance? If you can, please make sure to scrub out any sensitive information from there. If you still need help with this and can't directly share any further data with us, then I suggest you open a support ticket with Snowflake.
