### ISSUE TITLE
no 1.6.9 release branch and tag v1.6.9 is not in any known branch and preview releases are exposed at confluent hub

### ISSUE THREAD

**Issue by simbo1905** [snowflakedb/snowflake-kafka-connector#516]
The latest release shown on GitHub is currently 1.6.9. If you click to the tag v1.6.9 the github UI displays: 

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository. 

So if I fork then I don't get that commit/tag. 

There is no 1.6.9 release branch only release release-branch-v1.6.8. 

There are no 1.7.x releases but there are release branches. Okay fine. There are 1.8.x release marked as preview on github. Yet if you go to https://www.confluent.io/hub/snowflakeinc/snowflake-kafka-connector it shows "confluent-hub install snowflakeinc/snowflake-kafka-connector:1.8.2" as the command to run. yet that is marked as a preview release on github. if you click the download link that also pulls down the preview release. 

Can you please:

a) ensure that there is a latest release 1.6.9 commit is in on a branch in this repo (ideally named release-branch-v1.6.9)
b) clarify if the 1.8.x releases being advertised to the world at  https://www.confluent.io/hub/snowflakeinc/snowflake-kafka-connector are indeed production ready given as they are not flagged as the latest release on github and are also marked as preview release on github. 

Thanks!

**Comment by sfc-gh-tzhang** [comment]
Thanks for the input, the next stable, non-preview version (1.9.0) will be released next week and we will make sure it has the correct tag
