### ISSUE TITLE
Log verbosity in v1.8.2

### ISSUE THREAD

**Issue by vtstanescu** [snowflakedb/snowflake-kafka-connector#517]
Hello, there!

I'm running the Snowflake connector in [Amazon MSK Connect](https://docs.aws.amazon.com/msk/latest/developerguide/msk-connect.html) and updated from version 1.8.1 to 1.8.2.
I've noticed a big increase in logging from the `SnowflakeSinkTask` [class](https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/SnowflakeSinkTask.java#L328) where most of the messages are like the below:

```
[Worker-04e8a53a8bf0c26d2] [2022-12-13 07:16:41,590] INFO [snowflake-sink|task-1] [SF_KAFKA_CONNECTOR] [KC:691028928|SfTask[ID:1.1, #6]] calling put with 4 records (com.snowflake.kafka.connector.SnowflakeSinkTask:107)
[Worker-04e8a53a8bf0c26d2] [2022-12-13 07:16:41,590] INFO [snowflake-sink|task-1] [SF_KAFKA_CONNECTOR] [KC:691028928|SfTask[ID:1.1, #6]] successfully called put with 4 records, execution time: 0 seconds (com.snowflake.kafka.connector.SnowflakeSinkTask:107) 
```

This increased the log size, at least for our workload, from a couple of hundred MBs to over 20 GB (2 weeks retention).
These messages don't look particularly useful for the `INFO` level and seem too verbose. I'd like to suggest moving them to the `DEBUG` level.

Possibly an improvement in logging would be to have the # of records and total size when flushing the buffer to Snowpipe (`SnowflakeInternalStage` [class](https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/internal/SnowflakeInternalStage.java#L185)) to understand the performance of the connector.

**Comment by sfc-gh-tzhang** [comment]
@sfc-gh-rcheng could you help with this case? Thanks!

**Comment by sfc-gh-rcheng** [comment]
Thanks for the heads up on the logging. I've changed the log level to debug and removed a couple of logs. We are looking into adding more metrics around the buffer flush on Snowpipe as well
