### ISSUE TITLE
Unsupported feature: ENABLE_SCHEMA_EVOLUTION

### ISSUE THREAD

**Issue by JonathonO** [snowflakedb/snowflake-kafka-connector#530]
Hi,

We're trying to test out the schema evolution feature that's available but facing an "unsupported feature" exception. We're aware it's in private preview and had requested for it to be enabled on the Snowflake account. As far as we knew, it had been enabled.

Does this exception mean it's not enabled? How can we confirm?

**Comment by streamkap** [comment]
For clarity, this is happening here in the sink

if schematization is enabled, it is always creating a basic table, then doing alter table <name> set ENABLE_SCHEMA_EVOLUTION = true;, then doing show tables like '<name>' and checking that enable_schema_evolution == "Y" 

It is during this alter table statement it errors with unsupported feature.

**Comment by sfc-gh-tzhang** [comment]
The ENABLE_SCHEMA_EVOLUTION check is also in PrPr and needs to be enabled on the account. We do have an internal doc explains the enablement process, please work with the your sales to enable everything that is required

**Comment by streamkap** [comment]
Thanks @sfc-gh-tzhang

**Comment by sfc-gh-xhuang** [comment]
Now available to everyone in preview: https://docs.snowflake.com/release-notes/2023-07#schema-detection-and-evolution-for-kafka-connector-with-snowpipe-streaming-preview
