### ISSUE TITLE
Wildcards/regex usage in snowflake.topic2table.map

### ISSUE THREAD

**Issue by alonpr** [snowflakedb/snowflake-kafka-connector#534]
Does the parameter `snowflake.topic2table.map` accept wildcards or regex?

For example, if I have topics: `topic.1` , `topic.2` , `topic.3` ... `topic.99` and I want all of them to map to a single table: `table_x` then `snowflake.topic2table.map = topic.*:table_x` would be very helpful. 
Is it currently supported in any version of the connector?

**Comment by sfc-gh-rcheng** [comment]
This capability was added in this [commit](https://github.com/snowflakedb/snowflake-kafka-connector/pull/628/files). Closing out this issue, please reopen if you have any concerns
