### ISSUE TITLE
Connector PUTs messages in Stage even when deserialization fails

### ISSUE THREAD

**Issue by aidan-melen** [snowflakedb/snowflake-kafka-connector#537]
The issue is related to the configuration of the Kafka Connect connector and its interaction with Schema Registry. The Kafka Connect connector instance failed to validate the SSL cert for Schema Registry which resulted in a failure to deserialize AVRO messages. We could see the following error logs:

```
{"log":"PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n","stream":"stdout","time":"2023-02-06T20:37:21.520001468Z"}
[ERROR] 2023-02-06 20:36:48,742 [task-thread-my-connector-0] com.snowflake.kafka.connector.records.SnowflakeConverter error - [SF_KAFKA_CONNECTOR] [KC:238227321] failed to parse AVRO record
[INFO] 2023-02-06 20:36:48,745 [task-thread-my-connector-0] com.snowflake.kafka.connector.internal.SnowflakeConnectionServiceV1 info - [SF_KAFKA_CONNECTOR] [KC:xxxxxxx] put file: my-connector_257759425/TABLE_NAME/1/8878534_value_1675715808398.gz to table stage: TABLE_NAME
```

It looks like the deserialization is failing. At which point no data should be shipped to Snowflake. However, we are seeing a successful `PUT` operation for the same connector despite a complete failure to deserialize the message(s).

Here is a visual understanding of the failure:

![Screen Shot 2023-02-07 at 8 13 24 PM](https://user-images.githubusercontent.com/54326778/217419560-16b2d092-37ee-4077-a621-f3ac38c58f57.png)

The Snowflake Avro Convert likely has a bug that prevents it from failing when a record is unsuccessfully deserialized.

**Comment by aidan-melen** [comment]
Just found [this](https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/records/SnowflakeAvroConverter.java#L45-L46) in the code:

**Comment by aidan-melen** [comment]
`value.converter.break.on.schema.registry.error` should default to `true`

**Comment by aidan-melen** [comment]
What is the reasoning behind `value.converter.break.on.schema.registry.error=false` as the default? I am struggling to understand why you would want to send AVRO data that is failing to deserialize.

**Comment by sfc-gh-wfateem** [comment]
Hi @aidan-melen,
The purpose is to simply record the bad data that failed deserialization so you can refer to that for debugging. Assume the deserialization failed for a different reason other than the one you mentioned, for example, you received a bad/unexpected message that doesn't match the schema. You can use the offset number in the file name in order to inspect that message in Kafka, and take whatever corrective measures you need: Ignore, fix the bad message, and send it again to Kafka, etc...

**Comment by sfc-gh-wfateem** [comment]
@sfc-gh-japatel there is a legitimate concern here regarding costs. In this case, if there's a certificate issue then all these connections to the schema registry are bound to fail. We'll end up putting a number of files = 2 X messages on a stage. That can lead to a massive number of PUT statements depending on how many messages we end up receiving from Kafka Connect.

**Comment by sfc-gh-zgao** [comment]
> can lead to a massive number of PUT statements depending on how many messages we end up receiving from Kafka Connect.

@sfc-gh-wfateem @sfc-gh-japatel 
And this actually happened last week. Please see the details in SNOW-739627, where we can discuss this internally.

**Comment by sfc-gh-japatel** [comment]
Closing this in lieu of https://github.com/snowflakedb/snowflake-kafka-connector/issues/538#issuecomment-1442625857
