### ISSUE TITLE
Line feed on log messages

### ISSUE THREAD

**Issue by enzo-cappa** [snowflakedb/snowflake-kafka-connector#545]
Hello,

I'm seeing a line feed after the log level in log messages, for example:

```
[2023-02-15 18:20:38,060] INFO 
[SF_KAFKA_CONNECTOR] pipe SNOWFLAKE_KAFKA_CONNECTOR_SnowflakeSink_PIPE_issues_1, flush pipe: ReportingSnowflakeSink/table/1/32192492141_3219656730_1676485127526.json.gz (com.snowflake.kafka.connector.internal.SnowflakeSinkServiceV1)
```

This affects our logs processing pipelines, as any other log line is a single line of text. Or if there are multiple lines, consecutive lines are indented. 

Was it intentional to put the line feed after the log level?

By the way, of log pattern is `[%d] %p %m (%c)%n`

Thanks

**Comment by sfc-gh-tzhang** [comment]
This should be fixed in https://github.com/snowflakedb/snowflake-kafka-connector/pull/463 and is part of release 1.8.1
