### ISSUE TITLE
[REQUEST] Add log when COPY failed for a file

### ISSUE THREAD

**Issue by enzo-cappa** [snowflakedb/snowflake-kafka-connector#549]
It would be really helpful to have a log when a file failed to be copied. It would make debugging those problems easier.

I'll create a PR with a suggested approach. Needless to say, this is a suggestion and I'm completely open to change requests or feedback.

Thanks

**Comment by sfc-gh-rcheng** [comment]
Thanks for opening the PR for this issue, I've reviewed it and added follow up steps

**Comment by sfc-gh-rcheng** [comment]
PR has been merged, closing out issue
