### ISSUE TITLE
Limitation on buffer.size.bytes or file size?

### ISSUE THREAD

**Issue by alonpr** [snowflakedb/snowflake-kafka-connector#567]
Is there any known limitation for the `buffer.size.bytes` parameter or the uploaded file size?

When I'm increasing the parameter `buffer.size.bytes` over 1.5GB, I'm getting the following error:

> caught an exception for operation:UPLOAD_FILE_TO_INTERNAL_STAGE_NO_CONNECTION with message:-2044911229 (com.snowflake.kafka.connector.internal.InternalUtils)

Any value under 1.5GB (I tried 1.0, 1.1 ... 1.4GB) works fine. 
I'm not sure if it's due to the parameter value or the actual file's to be uploaded size.

**Comment by sfc-gh-japatel** [comment]
Seems like the limitation from Java's StringBuilder https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/java/lang/AbstractStringBuilder.java#L207-L215

**Comment by sfc-gh-japatel** [comment]
Closing this since this is a limitation from Java and we dont plan to make any changes in the architecture.
