### ISSUE TITLE
Is the delivery guarantee really exactly once?

### ISSUE THREAD

**Issue by rloeffel** [snowflakedb/snowflake-kafka-connector#570]
I'm using the new streaming api and according the documentation the delivery guarantee is exactly once https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka#exactly-once-semantics

I checked your source code and I can see that there you try to synchronize the offsets. But I cannot believe that this is possible without evaluation of the offset on snowflake itself. I give you an example:

1) Lets assume we have a connector task T1 that runs very slowly and the connection to kafka gets broken
2) Kafka will reassign the partition to another task T2
3) Task T2 will get the snowflake offset which is still 100 (just for example)
4) Task T1 and T2 will both write the same records to snowflake -> at least once

The problem here is that this zombie task is still running and you will not be able to synchronize it without the use of snowflake. Can you confirm or deny?

**Comment by rloeffel** [comment]
Thank your for your response. I was not aware that there can only be one consumer at a time. I'll check it out

**Comment by sfc-gh-japatel** [comment]
Just clarifying, there can be only one client (acquiring lock for a channel). 

[Consumer is a different term used in kafka world. There can be multiple consumers of a kafka topic]

Closing this issue, feel free to reopen.
