### ISSUE TITLE
NullPointerException on keySchema for keyless messages

### ISSUE THREAD

**Issue by JonathonO** [snowflakedb/snowflake-kafka-connector#582]
In our case, the source data comes from database tables without primary keys (we're using customised Debezium Connectors), which the Sink (v1.9.1) doesn't currently support.

Is this feature on the roadmap?

**Comment by sfc-gh-wfateem** [comment]
Hi @JonathonO,

It shouldn't matter if your messages have a key or not. A key can be null in Kafka, and I'm not aware of this being a problem in our connector. Are you running into a problem processing keyless messages from your topic? If so, can you share what error(s) you're seeing and what configuration you're using?

**Comment by sfc-gh-tzhang** [comment]
@JonathonO You probably have schematization enabled?

**Comment by JonathonO** [comment]
@sfc-gh-tzhang yes, correct:
```
    ...
    "snowflake.enable.schematization": "true",
    "snowflake.ingestion.method": "SNOWPIPE_STREAMING",
    ...
```

**Comment by sfc-gh-tzhang** [comment]
Interesting, I believe schematization only require the record.valueSchema to be not null, but not record.keySchema. Yes, could we have the full configuration as well as the log file?

**Comment by sfc-gh-wfateem** [comment]
Hey @JonathonO,

Would you be able to provide the configuration and the full error stack?
