### ISSUE TITLE
SnowflakeAvroConverter formats bytes as ISO_8859_1 string

### ISSUE THREAD

**Issue by tom-j-irvine** [snowflakedb/snowflake-kafka-connector#599]
When using the `SnowflakeAvroConverter`, records that contain binary values (`BYTES`) end up formatted as ISO_8859_1 strings.  This is because the `parseAvroWithSchema()` method simply calls `toString()` on the `GenericRecord`.

This is an issue because there is no way in Snowflake to convert this back to binary.  The `TO_BINARY()` function only accepts formats of HEX, BASE64, or UTF-8.  If the string was Base64 encoded (like other converters are doing), it could easily be converted with `BASE64_DECODE_BINARY()`

**Comment by sfc-gh-japatel** [comment]
Can you confirm the behavior with Community/Confluent Avro converter? `io.confluent.connect.avro.AvroConverter`

**Comment by tom-j-irvine** [comment]
With the community converter, you get base64 - this was my initial workaround, but I also need to allow tombstone messages, so that wouldn't allow me to use it.  Another difference between the two would be that some of the date/time logical types are handled correctly (back to actual dates or times) by the confluent converter, but the SnowflakeAvroConverter leaves this values "raw" (so, we get int values, not dates/times).

**Comment by tom-j-irvine** [comment]
To add a bit more detail comparing the `SnowflakeAvroConverter` with the confluent `AvroConverter`

With `bytes`:
* Confluent encodes as base64, so I can do `BASE64_DECODE_BINARY(RECORD_CONTENT:SomeField)`
* Snowflakes encodes as a string, so I tried `TO_BINARY(CAST(RECORD_CONTENT:SomeField AS STRING), 'UTF-8')` but this only worked on some values - any time the ISO_8859_1 string deviated from UTF-8, everything went to mush

With logical type `date`:
* Confluent turns the int into a date, so I can do `TO_DATE(RECORD_CONTENT:SomeField)`
* Snowflake keeps the int value, so I have to do `TO_DATE(DATEADD('dd', RECORD_CONTENT:SomeField, '1970-01-01'))`

With logical type `time-millis`:
* Confluent turns the int into a time, so I can do `TO_TIME(RECORD_CONTENT:SomeField, 'HH24:MI:SS.FF3+TZHTZM')`
* Snowflake keeps the int value, so I have to do `TO_TIME(TIMEADD('ms', RECORD_CONTENT:SomeField, '1970-01-01'))`

Other logical types that I haven't used that would likely behave similarly:
* time-micros
* timestamp-millis
* timestamp-micros
* uuid

The one logical type that is being handled the same is `decimal`

Again, the only one where there isn't a usable workaround is `bytes`, but the others aren't necessarily ideal.

Thanks for considering the issue.

**Comment by sfc-gh-gjachimko** [comment]
@sfc-gh-rcheng could we close this issue? does your PR addresses all the listed issues?

**Comment by tom-j-irvine** [comment]
Since I opened the issue, this is my current situation:
* The PR has allowed me to switch to snowpipe streaming using the community converter.  So, my personal needs have been met - Thank You! to @sfc-gh-rcheng for that.
* However, I don't believe the original issue with the SnowflakeAvroConverter is any different - it appears that it still doesn't handle logical types correctly.  If that is by design or doesn't matter to anyone, I'm certainly okay with the issue being closed.

**Comment by sfc-gh-gjachimko** [comment]
hi, thanks for reply!
i will close the issue as there is a workaround. if that still is the case for somebody, we can always try to reiterate it.
