### ISSUE TITLE
snowflake sink with merge instead of copy to a non variant based table

### ISSUE THREAD

**Issue by pankajagarwal** [snowflakedb/snowflake-kafka-connector#603]
I am using the snowflake sink connector with kafka connect and it works great but I don't think it's optimal use of compute the way we have it setup.

So, we have an existing table which this snowflake sink connector complains about structure mismatch. but it create a 2 column variant table, internal stage and pipe (all 9 yards). The data flows correctly and the connector is correctly deleting files in internal stage after they are processed.

The challenge I am running into is that i have to create another task to merge data from this new table with variant to the existing table that runs on a schedule which is processing same data multiple times until the cleanup task cleans up and sometimes the merge is taking too long and cleanup is deleting the data even before merge could process the same.

Is it possible to customise the pipe to run the merge on the files in internal stage via this connector instead of the additional task and cron ?

I don't see an option with the current documentation or may be I am missing to notice the same.

**Comment by sfc-gh-japatel** [comment]
Hi @pankajagarwal that is right understanding. 
We currently do not support modifying pipe/table schema. 

Please try out kafka connector with snowpipe streaming (in pupr) with schematization enabled. 

Schematization is currently unsupported with snowpipe based kafka connector and merge/streams and tasks on two column variant column is the right thing to do.

**Comment by pankajagarwal** [comment]
@sfc-gh-japatel thanks for your response. You mind sharing the documentation link on the connector you are suggesting to try here.

**Comment by sfc-gh-xhuang** [comment]
It's the same connector but different ingestion method: https://docs.snowflake.com/user-guide/data-load-snowpipe-streaming-kafka

However schematization is a private preview (not documented above) feature that you will need to ask your Snowflake account team to enable for you

**Comment by sfc-gh-japatel** [comment]
Feel free to try out the new connector and we are open for feedback. Closing this issue.
