### ISSUE TITLE
Why does the connector name have to be a valid Snowflake identifier? 

### ISSUE THREAD

**Issue by rmoff** [snowflakedb/snowflake-kafka-connector#62]
c.f. this issue https://github.com/snowflakedb/snowflake-kafka-connector/issues/61

Why is the connector enforcing that its name (an internal Kafka Connect identifier) being a valid Snowflake identifier? If the connector is using the connector name for something on the Snowflake side then maybe it should handle the appropriate transformation to sanitise it as required itself.

**Comment by binglihub** [comment]
https://github.com/snowflakedb/snowflake-kafka-connector/pull/115
