### ISSUE TITLE
Query performance degradation after switching to Snowpipe Streaming 

### ISSUE THREAD

**Issue by alexnikitchuk** [snowflakedb/snowflake-kafka-connector#626]
After switching from Snowpipe to Snowpipe Streaming we observed enormous query performance degradation: before the switch, query execution time was around 3 seconds, after - 80 seconds.
Snowflake support found the root cause: when Snowpipe Streaming was used for ingestion, it changed the table to a hybrid table. This negatively impacted queries and the table cannot be reverted back.
The workaround was to recreate the table and reload the data from the old one.

**Comment by sfc-gh-japatel** [comment]
Hi @alexnikitchuk what version of connector are you using?

**Comment by sfc-gh-japatel** [comment]
Also Hybrid table is not a unistore table, it is a table ingesting data through snowpipe streaming. (We had naming issues internally and we will communicate it with support)

**Comment by alexnikitchuk** [comment]
@sfc-gh-japatel it is 1.9.1

**Comment by sfc-gh-asen** [comment]
Hey, would you mind sharing the query IDs with slow and fast execution time? I'd be happy to look at it and investigate the issue

**Comment by alexnikitchuk** [comment]
> Hey, would you mind sharing the query IDs with slow and fast execution time? I'd be happy to look at it and investigate the issue

There is a case with all details 00509494 if you have access.
Queries:
Query ID 01abc605-0302-71c4-0000-f6b91f0340ca execution time 2.6 sec
Query ID 01abc605-0302-71de-0000-f6b91f02c4ae execution time 82 sec

**Comment by sfc-gh-xhuang** [comment]
We have investigated the performance issue more and have a fix rolling out. This can be enabled early on any accounts that face this issue.

**Comment by alexnikitchuk** [comment]
@sfc-gh-xhuang and how to enable it?

**Comment by alexnikitchuk** [comment]
thanks @sfc-gh-xhuang ! just checked the old table and it is as fast as it was before the issue.
Does it mean we can safely switch over to Snowpipe Streaming without any query performance consequences?

**Comment by sfc-gh-xhuang** [comment]
You can definitely use Snowpipe streaming for more testing but note that it is not yet generally available but will be soon in the next few months.
At GA is when we recommend fully moving over production workloads.

**Comment by alexnikitchuk** [comment]
hey @sfc-gh-xhuang we switched over to snowpipe steaming a few weeks ago. Yesterday faced exactly the same issue with query performance. Not sure how but can it be related to snowpipe streaming?

**Comment by sfc-gh-xhuang** [comment]
@alexnikitchuk Can you share some queryids? Do you have a support case open? 
This might be caused by a different issue.

If you are using the Kafka Connector, I highly recommend using version 2.1.0, which has some more optimizations
Previous version 1.9.4+ have the one_client_optimization option available but not default set to true. 
If your throughput is less than 100MB/s, I recommend setting that to true.

**Comment by alexnikitchuk** [comment]
Hey, yeah it was a regression issue with table clustering and it is fixed
now.
