### ISSUE TITLE
Consumer Group Lag metrics on 1.9.2

### ISSUE THREAD

**Issue by HenkvanDyk** [snowflakedb/snowflake-kafka-connector#629]
After deploying the Snowflake Kafka Connector version 1.9.2, all consumer group metrics related to Snowflake connectors increased by a few orders of magnitude.

Our average consumer group lag for 7 days went from 93 to 6 000 000.

I've confirmed that sinks to Snowflake are still working and messages are consumed, thus the issue is likely related to the consumer's acknowledge of commit to the `__consumer_offsets` topic.

Component | Version
-- | --
Kafka | MSK v3.3.3
Kafka Connect | 7.3.2 from Confluent (self managed)
Schema Registry | 7.3.2-debian-11-r0
Snowflake Sink Connector | 1.9.2
Snowflake Ingestion Mechanism | SNOWPIPE

**Comment by HenkvanDyk** [comment]
Consumer group lag metrics resolved by reverting to Snowflake connector 1.9.1

**Comment by sfc-gh-tzhang** [comment]
@HenkvanDyk Please use 1.9.1 as a workaround for now if you're using Snowpipe instead of Snowpipe Streaming and we will let you know once there is a update

**Comment by sfc-gh-tzhang** [comment]
This should be fixed in 1.9.3, please give it a try and let us know if there is still an issue
