### ISSUE TITLE
Docker image build

### ISSUE THREAD

**Issue by turtlelovesshoes** [snowflakedb/snowflake-kafka-connector#64]
Hi I wanted to cross reference this issue: 
https://community.snowflake.com/s/question/0D50Z00009UvjWGSAZ/build-a-combined-docker-image-for-snowflakekafkaconnector-with-cpkafkaconnectbase-to-deploy-on-kafka-connect-cluster

I am not sure how to troubleshoot it if you have a minute.

**Comment by rmoff** [comment]
I've answered this at https://stackoverflow.com/questions/58327092/build-a-combined-docker-image-for-snowflake-kafka-connector-with-cp-kafka-connec/58976359#58976359
