### ISSUE TITLE
Parsing JSON fields directly in the connector

### ISSUE THREAD

**Issue by omrikurtz** [snowflakedb/snowflake-kafka-connector#648]
Re-opening from https://github.com/snowflakedb/snowflake-kafka-connector/issues/179

A well needed feature that can save some folks a lot of money on SQL transformations.

Currently, the connector only allows to insert RECORD_METADATA and RECORD_CONTENT.
What I'd like is be able to specify a schema for what keys to extract from RECORD_CONTENT and add it to separated columns in the table.

**Comment by Elly-Mandliel-Forter** [comment]
This feature is absolutely necessary, +1!

**Comment by sfc-gh-japatel** [comment]
Hello all, @omrikurtz and @Elly-Mandliel-Forter 
We are working on this feature and it is in private preview mode with Snowpipe Streaming. 
https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka - This is in PuPr 

The schematization feature that you all requesting is still in PrPr and needs to be enabled on server side. We will soon make this available as PuPr feature. 

If you all want, I can enable this preview feature for you on a database that you might try it out. Just give us account name, deployment and database name. 

Thank you all for your patience on this one. 

CC: @sfc-gh-xhuang

**Comment by sfc-gh-rcheng** [comment]
@omrikurtz @Elly-Mandliel-Forter Is this a feature you'd like to try out? Otherwise may I close out this issue?
