### ISSUE TITLE
Performance tuning in Amazon MSK

### ISSUE THREAD

**Issue by vtstanescu** [snowflakedb/snowflake-kafka-connector#661]
Hello!

## Short description
This is more of a question, not sure if it's an actual issue or not.
**Q:** What are the guidelines for tuning the performance of the Snowflake Kafka Connector when we have consuming lag issues?

## Kafka Connect configuration
We are using the Snowflake Kafka Connector in Amazon MSK Connect, a managed Kafka Connect service offering from AWS with the following connector configuration:
```properties
connector.class=com.snowflake.kafka.connector.SnowflakeSinkConnector
tasks.max=2
topics=topic1,topic2,topic3,topic4,topic5

buffer.flush.time=300
buffer.size.bytes=209715200
buffer.count.records=200000

snowflake.url.name=<redacted>
snowflake.database.name=<redacted>
snowflake.schema.name=<redacted>
snowflake.user.name=<redacted>
snowflake.private.key=<redacted>
snowflake.private.key.passphrase=<redacted>

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=com.snowflake.kafka.connector.records.SnowflakeJsonConverter
```

We also use a worker configuration:
```
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=com.snowflake.kafka.connector.records.SnowflakeJsonConverter
config.providers.secretManager.class=com.github.jcustenborder.kafka.config.aws.SecretsManagerConfigProvider
config.providers.secretManager.param.aws.region=<redacted>
config.providers=secretManager
```

The compute capacity in MSK Connect is currently configured with 2 workers, each with 2 MSK Connect Units (MCUs), which means each worker has 2 vCPUs & 8 GiB memory, so across the whole connector we have 4 vCPUs & 16 GiB memory.

As can be seen from the connector configuration, we consume data from 5 topics with a buffer flush configuration as 5 minutes/200MiB/200k records.
We have a 2 broker Kafka cluster and each topic has 2 partitions.

## Producers' throughput
The producer side of Kafka is a backend application that writes to the topics with the following estimated throughputs (last 2 weeks' data):
topic1 - avg 2.15 MiB/s, max 3.28 MiB/s; messages: avg 323/s max 398/s (the messages is not actual Kafka topic metric, but from our backend)
topic2 - avg 1.14 MiB/s, max 1.83 MiB/s
topic3 - avg 14.5 KiB/s, max 47.7 KiB/s
topic4 - this can be ignored as it's rarely seeing data and when it does, it's very low quantity and size/message
topic5 - avg 34 KiB/s, max 389 KiB/s

As can be seen from the metrics from Amazon MSK, we don't seem to be hitting the limits of the data throughput of the cluster, brokers, or topic partitions.
Nonetheless, when the peak producers' time occurs, the Snowflake Kafka Connector is lagging with only one topic, `topic1`, the biggest in our application.

Worth mentioning that we don't see issues with the compute capacity of the connector, not even during producers' peaks.
We can try to enable more metrics (per-topic and per-partition) if it helps narrow down the issue, but we don't think this is a problem with Kafka, but rather Kafka Connect.
We are also looking to try the latest Snowflake Kafka Connector and try the Snowflake Streaming method, instead of Snowpipe.

### References
* https://docs.aws.amazon.com/msk/latest/developerguide/metrics-details.html

**Comment by sfc-gh-rcheng** [comment]
@sfc-gh-japatel has experience working with MSK, though it maybe different from what you are trying to do. Jay can you take a look?

**Comment by sfc-gh-wfateem** [comment]
Hey @vtstanescu,
I think the question is a bit open-ended, but I have a few thoughts.
For starters, when you say there's a consumer lag, how big of a lag are we talking and is that constant or is it continuously increasing?

Just looking at your metrics and along with your configurations, I can understand why you might be seeing a lag and it's not necessarily an issue. Take the following metric from your producer for topic 1:
```
topic1 - avg 2.15 MiB/s, max 3.28 MiB/s; messages: avg 323/s max 398/s
```
Here are the relative configurations for your Snowflake Kafka Connector:
```
buffer.flush.time=300
buffer.size.bytes=209715200
buffer.count.records=200000
```
For simplicity, let's say you're consistently producing 323 records per second. At that rate alone, and if we consider the `buffer.count.records` parameter alone, then the connector is only going to start writing out your output file after `200000 / 323 = 619 seconds` i.e. ~10 minutes.

At that rate, your `buffer.flush.time` parameter is your safety net, so it should be writing out the output file every 300 seconds (5 minutes). We're not going to commit the offsets until your entire batch of records is written out to a file, and then we confirm that this was ingested by Snowpipe at the backend. 

If you think about that message that first comes into your topic, and we say that's immediately read by Kafka Connect and passed to the Snowflake Kafka Connector, you can't expect that offset to be committed until 5 minutes have passed at least. So you can see why it would be natural to have a lag here. 

To bring down that latency, you would need to decrease the flushing time and number of records. The downfall of that is that you will end up driving your costs significantly since you're writing out a lot more files. Not to mention it can increase disk I/O activity on your nodes because of how frequently you're writing out your files on disk.

In order to really get a good idea of a benchmark for a particular environment, I suggest you start off by creating a single connector, with a single task that reads from a single topic with a single partition. You can then run your load tests to see how much a single task can handle, according to your requirements. As I mentioned previously, depending on your configurations you can expect a certain degree of consumer lag naturally. That performance and latency should be significantly better when you switch to SNOWPIPE_STREAMING as the ingestion method.

**Comment by sfc-gh-wfateem** [comment]
@vtstanescu I hope some of what I provided earlier was helpful, but let us know if you still have any questions.

**Comment by vtstanescu** [comment]
Getting back with some results from our experience, yet to do a benchmark in a separate environment. Interesting to see live performance nonetheless.

Check the 1st graph which shows BytesInPerSec & BytesOutPerSec (per partition - 5min average):
1. This huge red line is the BytesOutPerSec after the scale out I described in my last message. KC was catching up on the lagging partition.
Post going through this lag we reduced our KC connector back to 2 workers (2 MCUs each => 4 vCPUs, 8 GiB across the connector) with `tasks.max` set to `4`.
This means we have 3:1 ratio of partitions/task (as we have 6 topics with 2 partitions eachs => 12 partitions total). We do this to keep cost down as not all our topics produce at the same rate as the highest one.
2. BytesIn get bigger than BytesOut and as a consequence OffsetLag increases (see second graph).
My conclusion here is one partition gets less time in a task since that task handles other partitions too, though I'd expect the lag of the 2 partitions of the same topic to stay close to each other over time, but that's not the case (again, see second graph)
3. This dip is us recreating the connector to increase the worker count (to 3, from 2) and tasks.max (to 6, from 4), in an attempt to cope with increased production rate. The dip is in BytesOut, since the consumer is down, producer is still going so BytesIn doesn't spike down (increases actually with our traffic pattern)
4. After connector starts we can see it consumes at the same rate data is produced, although it is quite behind and it could do with consuming more to catch-up. It looks like it the ceiling is around 1.4MiB/s. For reference this topic gets over 7k messages/sec/partition at peaks, while the lows can be half of that at 3.5k messages/sec/partition.
5. BytesIn starts to reduce, we receive less traffic, but BytesOut remains consistent as KC has catching up to do.

### BytesIn & BytesOut PerSec (5 minutes average)
![image](https://github.com/snowflakedb/snowflake-kafka-connector/assets/611511/8a039cd0-28ca-418b-a361-f417bfe8c0c3)

### Offset Lag
![image](https://github.com/snowflakedb/snowflake-kafka-connector/assets/611511/3d1e5348-238b-4921-8b86-8265286507b0)

### MessagesInPerSec (5 minutes average)
![image](https://github.com/snowflakedb/snowflake-kafka-connector/assets/611511/ab033f32-24bc-4463-b5f8-254b10d23670)

**Comment by sfc-gh-wfateem** [comment]
Thanks for sharing @vtstanescu.
So what conclusions are you drawing out of this test, and what question(s)/issue(s) do you need help with in this issue? 
I want to be sure we understand what the purpose of this issue is and what it is we're trying to tackle here.

**Comment by vtstanescu** [comment]
I think I'm looking to understand 2 things here:
1. What are the limits of the connector? And, is there a way to estimate the amount of tasks, compute capacity and topic partitions needed to process a certain throughput?
Given the limit I see above, it looks to me that we might need to increase the number of partitions, though a conservative Kafka estimate is that a partition can provide 10MB/s throughput, but we don't see that on the consumer side.
Looking at the MessagesInPerSec metric, it looks like the `buffer.count.records` would be the first to be hit in order to flush a batch to Snowpipe, not the `buffer.flush.time` or `buffer.size.bytes`. Can this be our problem, though I don't see how?
2. Can the README of the project have more details about the inner workings of the connector. Details like how many tasks are created, based on what parameters, and what a task does?
These might be helpful for someone finding himself in a performance issue, like I presented, to pinpoint a bottleneck and then changer certain parameters based on data, rather than trial and error.
The trial and error part is what seems like we need to do for our case, test throughput in a separate environment and tweak parameters until we find what works, but the tweaking part doesn't seem to be done based on data & knowledge but rather just trying combinations.
Maybe I don't see/understand what I should look at to know what parameters to tweak to achieve desired performance, so that might be the end goal of what I want to get out of this issue.

**Comment by vtstanescu** [comment]
### Q&A
**Q**: What is your throughput target? Is that 10 MB/s then?
**A**: We don't need that much, but we can see at peaks we produce ~1.6MB/s per partition and this will grow (until a point we start using more partitions for the topic in question). So we expect the consumer (SF Kafka Connector) to keep up with that, while we are within the 10 MB/s partition throughput.
Again, the 10 MB/s is a conservative, general expected throughput of a Kafka partition, not our current throughput.

**Q**: And is the expectation here to process that using one single task?
**A**: If we are talking about the 10MB/s per partition, it would be nice to know that the SF Kafka Connector can process that much as long as Kafka can give it that throughput, but understanding there will be some overhead flushing to Snowpipe, we expect that to be lower, but not 1.4MB/s as we see in our production environment.

**Q**: Concerning your data, how large are your messages (average, and maximum size)?
**A**: For this topic that has this issue the average message size is 1.1 KiB, maximum goes to 5.65 KiB, while the minimum is 0.8 KiB. I got these figures from the Snowpipe table using `LENGTH(RECORD_CONTENT)`.
The maximum value seems an outlier, I'll check separately on that with the dev team.

**Q**: Are the messages in Avro format or plain String? What converters are you using to serialize and deserialize your data? Can you give us an example of what your message looks like structure-wise?
**A**: Messages are one-line JSONs to keep message size to a minimum.
The `key.converter` is `org.apache.kafka.connect.storage.StringConverter`, though we don't key our messages, thus their are round-robin balanced between the 2 partitions.
The `value.converter` is `com.snowflake.kafka.connector.records.SnowflakeJsonConverter`

**Q**: Is your MSK cluster on AWS in the same region as your Snowflake account? If not, what regions are involved here?
**A**: All infrastructure (MSK, MSK Connect & Snowflake account) is in the same region of the AWS cloud. We don't use AWS PrivateLink to connect to Snowflake.

**Q**: Finally, for all these metrics you have provided, are we still talking about the ingestion method SNOWPIPE, or are we talking about SNOWPIPE_STREAMING?
If you haven't tried SNOWPIPE_STREAMING then can I ask you to run another quick test and let us know if you see an improvement in throughput and whether or not that meets your expectations?
**A**: It's SNOWPIPE, without streaming. We are going to try it, but I'm pending a dev environment in Snowflake to test it out before rolling it into production. I'll present more info when after I complete that test.

### KC Tasks assignment and MSK Connect

Thank you for sharing the links regarding how KC creates and assigns tasks. This is been very helpful for me (with less than 1 year experience operating Kafka & KC).
The comments in this ticket, https://issues.apache.org/jira/browse/KAFKA-13136, made me think whether this can be an issue in MSK Connect, which uses Kafka 2.7.1 version for the client library. Amazon doesn't support other versions for MSK Connect, though for MSK (Kafka clusters) they support more versions (we currently use 3.3.1).
Back to the issue, I found the following interesting log messages (remind you that we use v1.8.1 of the Snowflake Kafka Connector):

> [Worker-0178b67d48ee8ac28] [2023-07-07 13:39:23,213] INFO [REDACTED_MSK_CONNECT_CONNECTOR_NAME|task-3] [SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:3]:open, TopicPartition number: 0 (com.snowflake.kafka.connector.SnowflakeSinkTask:244)
[Worker-0178b67d48ee8ac28] [2023-07-07 13:39:23,239] INFO [REDACTED_MSK_CONNECT_CONNECTOR_NAME|task-0] [SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:0]:open, TopicPartition number: 6 (com.snowflake.kafka.connector.SnowflakeSinkTask:244)
[Worker-00c15c99fba9659ce] [2023-07-07 13:39:23,215] INFO [REDACTED_MSK_CONNECT_CONNECTOR_NAME|task-4] [SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:4]:open, TopicPartition number: 0 (com.snowflake.kafka.connector.SnowflakeSinkTask:244)
[Worker-00c15c99fba9659ce] [2023-07-07 13:39:23,238] INFO [REDACTED_MSK_CONNECT_CONNECTOR_NAME|task-1] [SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:1]:open, TopicPartition number: 6 (com.snowflake.kafka.connector.SnowflakeSinkTask:244)
[Worker-0d928ae7cb870fd2b] [2023-07-07 13:39:23,214] INFO [REDACTED_MSK_CONNECT_CONNECTOR_NAME|task-2] [SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:2]:open, TopicPartition number: 0 (com.snowflake.kafka.connector.SnowflakeSinkTask:244)
[Worker-0d928ae7cb870fd2b] [2023-07-07 13:39:23,215] INFO [REDACTED_MSK_CONNECT_CONNECTOR_NAME|task-5] [SF_KAFKA_CONNECTOR] SnowflakeSinkTask[ID:5]:open, TopicPartition number: 0 (com.snowflake.kafka.connector.SnowflakeSinkTask:244)

I cross checked this realization with `kafka-consumer-groups.sh --describe --members --verbose` and `kafka-consumer-groups.sh --describe --state` and I think we pinpointed our problem:
**No matter how big we make `tasks.max` the default RangeAssignor of the consumer group, will not be assigning any partitions to more tasks than the highest partition count of a topic from the topics consumed by the connector.**

This seems to be the issue of MSK Connect, using v2.7.1 of Kafka client library. We have another consumer group used by AWS Lambda ESM and that has the strategy `cooperative-sticky`.
AWS seems to point this out here: https://docs.aws.amazon.com/msk/latest/developerguide/msk-connect-troubleshooting.html

We will try the `CooperativeStickyAssignor` to see if this improves our performance, assuming the Snowflake Kafka Connector's poor performance was caused by the fact that one task had to deal with 6 partitions.

**Comment by vtstanescu** [comment]
We fixed our issue by using a different assignor than the default `RangeAssignor` one. We ended up with `StickyAssignor` one (eager rebalancing), instead of the `CooperativeStickyAssignor` that does incremental cooperative rebalancing. That's because the Kafka Connect framework has a bug in 2.7.1 causes it to stop storing offsets in the consumer group when a incremental cooperative rebalancing strategy is used.
See the [Kafka bug report](https://issues.apache.org/jira/browse/KAFKA-12487) for more details.

Unfortunately Amazon only support this version of the Kafka client library in their MSK Connect service.
From the Snowflake Kafka Connector side, everything looks fine, our performance figures look good now.

**Comment by sfc-gh-wfateem** [comment]
Thanks for the update @vtstanescu 
Can you share what your throughput looks like now and how many tasks you're using?

**Comment by vtstanescu** [comment]
The throughput increased overall as the producer is also producing more data, the key take away is the connector is keeping up with the production rate, and we have no more lag (than the buffer values we use). We are currently operating with 6 tasks, so we have 2 partitions/task across all the topics the connector subscribes to.

We'll be looking to test a few things in the near future:
* Maximum throughput of one task and one partition - this should give us an idea of when we need additional tasks in the connector and/or additional partitions in the topic
* With current setup, we might try to get lower again on workers, from 3 to 2 and have tasks.max to 4 and see if it can handle all the throughput from all the partitions - this is key for cost management.
Especially since some of the topics are low throughput, so we expect having their partitions in the same task with a higher throughput topic/partition wouldn't affect the lag of the higher throughput one.
Could be useful here to learn more about how Kafka Connector framework and/or SF connector handles multiple partitions assigned to the same task, and what could be the overhead, thus helping estimate the right balance of partitions/task or data-rate/task.
* Snowflake Streaming in Kafka Connect

**Comment by jsrcodes** [comment]
Hi @vtstanescu , thanks for this discussion. We are also running into a similar issue, but in our case we use Snowpipe Streaming. I suspect in our case, the lower retention and frequent Network I/O to shift the rolled segments to remote storage is likely affecting the broker's egress to consumers. The retention settings we use: segment.ms = 10 minutes, local.retention.ms = 15 minutes, remote storage retention = 3 days). 

May I know your EBS storage volume per broker? We currently set it to 80GB which is why we went with such a shorter local retention.

**Comment by vtstanescu** [comment]
@jsrcodes Sounds like you are looking at the Kafka broker being a problem, not the Snowflake KC connector, so it's outside the scope of this issue.
In my use case, we didn't touch the segment configuration, so it's Kafka's default (7d). That being said, we allocate way more storage for the brokers.
