### ISSUE TITLE
Snowflake converter and SMTs

### ISSUE THREAD

**Issue by lyuboxa** [snowflakedb/snowflake-kafka-connector#662]
Hey folks,

We have bunch of SMTs build to support our data flow and according to the documentation, we have to use the snowflake value converter which doesn't seem to be compatible with the transformations due to the record type (say not `STRUCT` et al).

What are the alternatives for this situation? Without the value converter set, I don't see any data coming through. 

Any particular reasons why the record conversion to snowflake record content record doesn't happen past the transforms pipeline? E.g. after `put`.

Any thoughts?

Thanks

**Comment by sfc-gh-rcheng** [comment]
**What are the alternatives for this situation? Without the value converter set, I don't see any data coming through.**
Can you use the `io.confluent.connect.avro.AvroConverter` or `org.apache.kafka.connect.json.JsonConverter` as value converters? Currently the Snowflake Sink Kafka Connector does not support SMTs with the Snowflake value converters ([documentation](https://docs.snowflake.com/en/user-guide/kafka-connector-overview#kafka-connector-limitations)).

**Any particular reasons why the record conversion to snowflake record content record doesn't happen past the transforms pipeline? E.g. after put.**
This connector just takes data from the Kafka topic and sends it to a Snowflake table. Unfortunately I don't believe we have any plans to support additional SMTs beyond the above converters.


Does that answer your question?

**Comment by lyuboxa** [comment]
@sfc-gh-rcheng thanks for the clarification, appreciate it.

From you comment, I gather that the `JsonConverter` should work just as well as the Snowflake Converter? I'm going to give it a go. 

I found a workaround for my SMT issues, but I'm running in another one related to this, here are my settings:

```
topics.regex = data-stream-(.*)
key.converter=org.apache.kafka.connect.json.JsonConverter
```

I have an SMT in place which extracts the topic name from a field `__topic`  in the key and sets it as the record topic. 
As expected, I have the stages, pipes and tables created based on the value of `__topic` (values of the field are a variation of  the prefix + suffix e.g. `data-stream-cars`, etc). I can see files uploaded in the stages, but nothing is materializing in the tables and I have no idea why. I don't see any errors in the logs. The only topic in Kafka is `data-stream-all` which contains all the data, the SMT in essence de-multiplexes the data in the topic using the record topic name. This works fine with debezium/jdbc connectors we use. 

Thank you!

**Comment by lyuboxa** [comment]
Quick update:
- Data is being staged properly, I checked the stage files and they are as expected in a per topic stage
- Pipe definition looks good too. 
- I tried using the copy into from stage to the table and this worked as expected.

It seems that for some reason the pipe is not copying data into the tables

**Comment by sfc-gh-rcheng** [comment]
I did a little more digging, would something like the following work for you? You'd need to know all of the topic names in the configuration though:
[Configuration](https://github.com/snowflakedb/snowflake-kafka-connector/blob/52f0a8a821f748b0715f49462a67b4b5cf1800fe/test/rest_request_template/travis_correct_native_complex_smt.json#L14-L20) to extract c1 integer and ignore c2 field
[Test](https://github.com/snowflakedb/snowflake-kafka-connector/blob/52f0a8a821f748b0715f49462a67b4b5cf1800fe/test/test_suit/test_native_complex_smt.py) that runs the above config and confirms that only c1 was ingested into the topic

Alternatively you could use [schema evolution](https://docs.snowflake.com/en/user-guide/data-load-schema-evolution), however all the data would be ingested into one table instead of multiple. If you need multiple tables, you could run a task to periodically split the table into multiple tables. Note that schema evolution is in PuPr

**Comment by sfc-gh-rcheng** [comment]
@lyuboxa Checking in - does the above work for you?

If so feel free to close out this issue, otherwise I'll close this in a week

**Comment by lyuboxa** [comment]
@sfc-gh-rcheng apologise for the tardiness, I was away for a bit and didn't follow up.

I managed to get my use case to work with the streaming functionality (no pipe/staging).

I did some digging as well, to figure out why it didn't work with pipes and it turned out the pipe copy wasn't being
triggered at all if they are created post init, and in my case (because messages had topics different than the `topics` property) pipes/stages were created on the go.  https://github.com/snowflakedb/snowflake-kafka-connector/blob/0f570ee4108b25f7899e5858f5afedffeb843e9c/src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java#L146-L154

In this case `ingestFiles` was never called it seems, which will trigger the stage.

I think the issue's description does not represent the issue. SMTs are not the issue per se. To reproduce the issue, the connect will need to consume a message from a topic `bar` but the record topic be set to `foo`. The message should end in table `foo` not bar.

**Comment by sfc-gh-rcheng** [comment]
Good to see it is working for you! 

Streaming has a different workflow than Snowpipe, so it should be calling the following method instead. Please note that streaming is still in PuPr, though GA should be coming soon.
https://github.com/snowflakedb/snowflake-kafka-connector/blob/0f570ee4108b25f7899e5858f5afedffeb843e9c/src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java#L239-L262

In terms of the issue, can you please clarify the ask if it is working for you now? I'm not too sure what 'The message should end in table foo not bar' means.

**Comment by lyuboxa** [comment]
> In terms of the issue, can you please clarify the ask if it is working for you now?

The connector is working as expected when:

```
snowflake.ingestion.method=SNOWPIPE_STREAMING
```

and not producing any data in the tables when 

```
snowflake.ingestion.method=SNOWPIPE
```
> I'm not too sure what 'The message should end in table foo not bar' means.

Let say a connector is configured like so

```
topics=foo
```

Kafka connect will consume from topic `foo` and deliver the [SinkRecord](https://kafka.apache.org/24/javadoc/org/apache/kafka/connect/sink/SinkRecord.html) to the Snowflake Connector. The record object has a field `topic`,  and that record is transformed and set to `bar`.  Here is a visualisation with the SMT flow.

![smt-progress](https://github.com/snowflakedb/snowflake-kafka-connector/assets/78747144/633d9ae5-6c68-4d63-82f3-2303cd8c7423)

**Comment by sfc-gh-rcheng** [comment]
Thank you for the detailed explanation, I understand what you're trying to accomplish here. 

What you are using is [Schema Evolution](https://docs.snowflake.com/en/user-guide/data-load-schema-evolution), which is only available with Snowpipe Streaming. This is why it worked for you with `snowflake.ingestion.method=SNOWPIPE_STREAMING`.

Please keep in mind that both Snowpipe Streaming and Schema Evolution are in [Public Preview](https://docs.snowflake.com/en/release-notes/preview-features), which means that it should not be used in production.

Are there any other concerns you have?

**Comment by lyuboxa** [comment]
Thanks! Appreciate the input, no other concerns.

**Comment by cchandurkar** [comment]
> I found a workaround for my SMT issues

@lyuboxa  what was the workaround? I'm trying to do the similar thing: SnowflakeSinkConnector + AvroConverter + SMT. But it does not look like it's picking up the transformed schema.

**Comment by lyuboxa** [comment]
> > I found a workaround for my SMT issues
> 
> @lyuboxa what was the workaround? I'm trying to do the similar thing: SnowflakeSinkConnector + AvroConverter + SMT. But it does not look like it's picking up the transformed schema.

What is the issue that you are having? I checked out #706 and the error is not related. In my case, the issue was related to modifying the topic name before the snowflake connector, which caused it to not flush the pipe. Using the streaming solved my issue.
