### ISSUE TITLE
Can't build views on tables from a share using snowpipe streaming

### ISSUE THREAD

**Issue by chrisluedtke** [snowflakedb/snowflake-kafka-connector#667]
I recently migrated my team's snowflake sink connectors to snowpipe streaming. We utilize shares to expose our landing tables to another snowflake account. In that other account, some views that select from those landing tables began to fail:

```
000603 (XX000): SQL execution internal error:
Processing aborted due to error 370001:2988582113; incident 9964366.
```

Note from Snowflake support:
> We confirmed this issue is presented for tables that are being populated using Snow pipe. These views that are failing are all accessing the Shared table from the Provider account, which are populated by Snow pipe. 
As a workaround:  on the provider, create a normal table with CTAS from the base table and share the regular table.
This is a known issue and our team is actively working on a fix. Sorry for the inconvenience.
The fix is expected to be released in the week of 25th July.

**Comment by sfc-gh-xhuang** [comment]
Thanks for reporting that issue, we are fixing it and it will be available before the end of July.

**Comment by sfc-gh-xhuang** [comment]
Hi @chrisluedtke This issue should be fixed now, can you please validate if you are still running into the issue?
