### ISSUE TITLE
Default value expressions not supported - snowpipe streaming

### ISSUE THREAD

**Issue by chrisluedtke** [snowflakedb/snowflake-kafka-connector#668]
My team adds a custom `inserted_at` column to our snowflake landing tables with a default value expression of `current_timestamp()`. This enables us to monitor insertion history and calculate end-to-end latency. But when testing snowpipe streaming, this column caused errors. Is there an alternative method to persist the snowflake landing time?

**Comment by WDoan** [comment]
This would be a greatly appreciated feature. Without schematization enabled, we have not come up with a way to prune data by timestamp based on the VARIANT/JSON blobs created by Snowpipe streaming. Using `EXPLAIN` the queries we end up executing end up doing an entire table scan even with a predicate on the tables created by Snowpipe streaming.

**Comment by chrisluedtke** [comment]
I've checked again, using snowflake connector v2.0.1 and debezium v2.2. The same error is present:
```
Snowpipe Streaming is not supported on the type of table resolved, or the table contains columns that are either AUTOINCREMENT, IDENTITY or has default value
```

**Comment by rhyswilliamsza** [comment]
We are also looking for this. I believe it's a limitation of Snowflake Streaming. Would it be possible to include this column as part of inserts?

**Comment by sfc-gh-xhuang** [comment]
@chrisluedtke @rhyswilliamsza How accurate do you need this timestamp to be?

For kafka connector w/ file-based Snowpipe support, default columns with current_timestamp() are cached and not 100% accurate of the actual insert time so the e2e latency calculation is not correct. 

For KC w/ Snowpipe Streaming, we can potentially add a similar value to record_metadata that is corresponding to the client_insert time in the short term. This too would be approximate but can still be more accurate than the current_timestamp() default column approach.

**Comment by toddwiese** [comment]
We are also looking for this, currently using v2.2.0.  We create the table first with an audit_timestamp defaulting to current_timestamp().  In our case, it doesn't need to be entirely accurate, as we have tasks that flatten or process the data when it lands, and it's used as a watermark.  

Parsing the record_metadata variant for the CreateTime or similar timestamp causes a full scan, as previously mentioned.

Another idea would be to add a configuration of some sort, ignore.defaults = true ?

**Comment by chrisluedtke** [comment]
Thanks @sfc-gh-japatel. A timestamp embedded in `record_metadata` would be great. While this would not improve clustering or prevent full scans, we intend to layer dynamic tables downstream. Those dynamic tables could achieve both efficient clustering and extracting the rough landing time from `record_metadata`.

> For kafka connector w/ file-based Snowpipe support, default columns with current_timestamp() are cached and not 100% accurate of the actual insert time so the e2e latency calculation is not correct.

The issue we're discussing relates to snowpipe streaming, which is not file-based. Would that concern still apply for row-based loading with snowpipe streaming? Like @toddwiese, we don't need the value to be very accurate. All of our deduplication/compaction of events is done based on LSN values from source databases. We use the landing timestamp for table clustering and sanity checks (counting event inserts by the hour and roughly analyzing end-to-end latency for large spikes).

**Comment by chrisluedtke** [comment]
This timestamp was added to `record_metadata` in https://github.com/snowflakedb/snowflake-kafka-connector/pull/833
