### ISSUE TITLE
Question/Clarification-Does snowflake-kafka-connector maintain multiple login session?

### ISSUE THREAD

**Issue by Ravi733499** [snowflakedb/snowflake-kafka-connector#677]
Hi , 
I have come across the situation where admin team has raised concern that we have huge number of active user sessions,
so was looking for clarification , how snowflake-kafka-connector login mechanism works?

Does it open always active session for processing the message ? if yes do we have any config attribute which can take care of closing login session post processing the kafka message?

below are the attributes in my configuration file:

 "connector.class":"com.snowflake.kafka.connector.SnowflakeSinkConnector",
    "tasks.max":"8",
    "topics":"*********",
    "snowflake.topic2table.map": "********",
    "buffer.count.records":"10000",
    "buffer.flush.time":"60",
    "buffer.size.bytes":"5000000",
    "snowflake.url.name":"*****************,
    "snowflake.user.name":"******",
    "snowflake.private.key":"******",
    "snowflake.private.key.passphrase":,
    "snowflake.database.name":"******",
    "snowflake.schema.name":"**********",
    "key.converter":"org.apache.kafka.connect.storage.StringConverter",
    "value.converter":"com.snowflake.kafka.connector.records.SnowflakeJsonConverter"

**Comment by sfc-gh-xhuang** [comment]
Which version of the connector are you using?

**Comment by sfc-gh-xhuang** [comment]
Can you please upgrade to 2.0.0? That is our latest version and is supported for GA usage. 

In version 1.9.4, we also introduced a 1 client change which would reduce the number of client connections that kafka connector open and instead uses more channels to reduce costs for the majority of use cases.

**Comment by Ravi733499** [comment]
Thank you for the response!!

just to reconfirm do you mean google analytics by GA?  

The other question I had - how the open sessions gets closed? 

once the kafka connect is down , would all the open session be closed by itself , or do i need to provide any property in configuration to take care.  our admin team has to do some update and they are looking for all the active session to be in closed state.

**Comment by sfc-gh-xhuang** [comment]
No GA means generally available for us. Previously we were in public preview but with the 2.0.0, Snowpipe Streaming is a fully supported ingestion method for Kafka Connector. 

I believe the open sessions should get closed by itself after some time. @sfc-gh-rcheng would you know?

**Comment by sfc-gh-rcheng** [comment]
Hi @Ravi733499 , we don't explicitly close the connection to Snowflake, however this connection does live on the connector and sink task threads. This means that when Kafka Connector shuts down, the connection will also be deleted.
