### ISSUE TITLE
Schema evolution issue

### ISSUE THREAD

**Issue by miramar-labs** [snowflakedb/snowflake-kafka-connector#686]
I have the new schema detection/evolution support enabled in my v2 snowflake sink connector. I can see it actually creating columns in the table ready for loading data... but as it tries to load, I get this:
  "message" : "Snowpipe Streaming is not supported on the type of table resolved, or the table contains columns that are either AUTOINCREMENT, IDENTITY or has default value."
  
  Now, I don't see any columns that are AUTOINCREMENT, IDENTITY or has default value in this new target table .. so what might I be missing here?

**Comment by sfc-gh-wfateem** [comment]
Hi @miramar-labs,
Are you using a transient table? The limitations are documented [here](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-overview#limitations). Do any of these apply to you?
If not, can you please run the following in Snowflake and provide the output?
```
select get_ddl('table', '<database.schema.table_name>');
```

**Comment by sfc-gh-tzhang** [comment]
+1, or the table is a transient schema or database

**Comment by miramar-labs** [comment]
The snowflake sink connector created the table .. so I don't think it's 'transient' ?

select get_ddl() output  :

`create or replace TABLE PERSON (
	RECORD_METADATA VARIANT COMMENT 'created by automatic table creation from Snowflake Kafka Connector',
	GENDER_CONCEPT_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	DAY_OF_BIRTH NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	MRN VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	LAST_NAME VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	ETHNICITY_SOURCE_CONCEPT_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	RACE_SOURCE_CONCEPT_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	GENDER_SOURCE_CONCEPT_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	MIDDLE_NAME VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	RACE_SOURCE_VALUE VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	CARE_SITE_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	BATCHID VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	LOCATION_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	YEAR_OF_BIRTH NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	SSN VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	PERSON_SOURCE_VALUE VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	GENDER_SOURCE_VALUE VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	ETHNICITY_CONCEPT_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	RACE_CONCEPT_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	MONTH_OF_BIRTH NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	ETHNICITY_SOURCE_VALUE VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	PROVIDER_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	BIRTH_DATETIME NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	FIRST_NAME VARCHAR(16777216) COLLATE 'en-ci' COMMENT 'column created by schema evolution from Snowflake Kafka Connector',
	PERSON_ID NUMBER(38,0) COMMENT 'column created by schema evolution from Snowflake Kafka Connector'
);
`

**Comment by miramar-labs** [comment]
also, the AVRO schema of the topic the snowflake sink is trying to load from is here:

`{
  "connect.name": "com.mycompany.streams.omop.avro.PERSON",
  "fields": [
    {
      "name": "person_id",
      "type": "int"
    },
    {
      "name": "gender_concept_id",
      "type": "int"
    },
    {
      "name": "year_of_birth",
      "type": "int"
    },
    {
      "default": null,
      "name": "month_of_birth",
      "type": [
        "null",
        "int"
      ]
    },
    {
      "default": null,
      "name": "day_of_birth",
      "type": [
        "null",
        "int"
      ]
    },
    {
      "default": null,
      "name": "birth_datetime",
      "type": [
        "null",
        {
          "connect.name": "io.debezium.time.Timestamp",
          "connect.version": 1,
          "type": "long"
        }
      ]
    },
    {
      "name": "race_concept_id",
      "type": "int"
    },
    {
      "name": "ethnicity_concept_id",
      "type": "int"
    },
    {
      "default": null,
      "name": "location_id",
      "type": [
        "null",
        "int"
      ]
    },
    {
      "default": null,
      "name": "provider_id",
      "type": [
        "null",
        "int"
      ]
    },
    {
      "default": null,
      "name": "care_site_id",
      "type": [
        "null",
        "int"
      ]
    },
    {
      "default": null,
      "name": "person_source_value",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "default": null,
      "name": "gender_source_value",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "default": null,
      "name": "gender_source_concept_id",
      "type": [
        "null",
        "int"
      ]
    },
    {
      "default": null,
      "name": "race_source_value",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "default": null,
      "name": "race_source_concept_id",
      "type": [
        "null",
        "int"
      ]
    },
    {
      "default": null,
      "name": "ethnicity_source_value",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "default": null,
      "name": "ethnicity_source_concept_id",
      "type": [
        "null",
        "int"
      ]
    },
    {
      "default": null,
      "name": "mrn",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "default": null,
      "name": "ssn",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "default": null,
      "name": "first_name",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "default": null,
      "name": "last_name",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "default": null,
      "name": "middle_name",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "default": null,
      "name": "batchID",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    }
  ],
  "name": "PERSON",
  "namespace": "com.mycompany.streams.omop.avro",
  "type": "record"
}`

**Comment by sfc-gh-tzhang** [comment]
Correct, but could you check whether the table is created in a transient schema or database?

**Comment by miramar-labs** [comment]
how do I check that?

**Comment by miramar-labs** [comment]
ok well i'm 99.9% certain the schema and or database is not transient .. but I don't know how to confirm that. 
Looking at the limitations link .. I spotted that `Default column value that is not NULL.`, and looking at my topic AVRO, I do see a lot of ` "default": null,` entries for various fields, so I manually evolved the AVRO, deleted all those... re-tried .. but still the same error ....

**Comment by sfc-gh-tzhang** [comment]
I think if you do SHOW DATABASES, the options field will show as TRANSIENT, see https://docs.snowflake.com/en/sql-reference/sql/create-database#examples

**Comment by miramar-labs** [comment]
ok so I can confirm neither the database or the schema is transient....

**Comment by miramar-labs** [comment]
I tried debugging the connector live on our cluster but the error is coming back from snowflake when the connector tries to open a channel to the table:

SnowflakeStreamingIngestChannel openChannelForTable()

this is where the error text comes from ... 

does this suggest our snowflake cluster is misconfigured somehow?

**Comment by sfc-gh-azagrebin** [comment]
Columns with collations are not supported (requirements in the doc).
There is e.g. `LAST_NAME VARCHAR(16777216) COLLATE 'en-ci'`

**Comment by miramar-labs** [comment]
hmm .. so that table was created by the connector .. how do I stop it from doing that?

**Comment by sfc-gh-tzhang** [comment]
Good point! The collation is probably set to case-insensitive at account/database/schema level, see https://docs.snowflake.com/en/sql-reference/collation#collation-control. Unfortunately, schematization + Snowpipe Streaming currently doesn't support any other collations, you need to create a separate database with the default collation instead.

**Comment by miramar-labs** [comment]
yes! :) So we disabled collation on _our_ database (it was set to 'en-ci' company-wide) :
alter database dev_kafka_test set DEFAULT_DDL_COLLATION = '';
Now it works!  
:)

**Comment by miramar-labs** [comment]
follow-up question:
there was a step mentioned in the notes about the need for doing this:
alter table DEV_KAFKA_TEST.OMOP_TEST.PERSON set ENABLE_SCHEMA_EVOLUTION = TRUE;
Q: If the table (PERSON) is _created by the snowflake connector_, do we still need to do this? Seems like a chicken-egg problem? Can this be set at the database level for all tables?

**Comment by sfc-gh-tzhang** [comment]
No, I don't think you need to do this. I think you can only set it on a table, similar to CHANGE_TRACKING

**Comment by miramar-labs** [comment]
So here is what I see... if I delete the PERSON table and re-run the connector, the connector will auto-create a PERSON table but with a single VARIANT(RECORD_METADATA) column. The table fails to evolve and spits out an error:

Caused by: org.apache.kafka.connect.errors.DataException: Error inserting Records using Streaming API with msg:The given row cannot be converted to the internal format: Extra columns: [birth_datetime, year_of_birth, race_concept_id, mrn, last_name, ethnicity_source_concept_id, person_source_value, provider_id, first_name, gender_source_concept_id, month_of_birth, location_id, day_of_birth, middle_name, gender_source_value, ethnicity_concept_id, race_source_value, care_site_id, ssn, batchID, race_source_concept_id, person_id, gender_concept_id, ethnicity_source_value]. Columns not present in the table shouldn't be specified

So then I stop the connector and apply :

alter table DEV_KAFKA_TEST.OMOP_TEST.PERSON set ENABLE_SCHEMA_EVOLUTION = TRUE;
GRANT EVOLVE SCHEMA ON TABLE DEV_KAFKA_TEST.OMOP_TEST.PERSON TO ROLE RBA_DATAOPS_KAFKA_DEV;

Then I restart the connector.. the table evolves with all the right columns and data is able to stream from my PERSON Kafka topic into the evolved Snowflake PERSON table.

But ideally I shouldn't have to stop and restart the connector ... seems clunky.

What is the alternative? Pre-cerate the PERSON table with, say, a single VARIANT column .. and apply the ALTER TABLE/GRANT commands to it? I guess I could tell the connector not to auto-create the tables in this scenario?

Or is there a better, more seamless way?

**Comment by sfc-gh-tzhang** [comment]
This is interesting, if the table is created by the connector, we will set ENABLE_SCHEMA_EVOLUTION = true by default, and the role used to create the table should have owner privilege already so we should be good. @sfc-gh-japatel (or Alec?) Do you think this behavior change might be related to the recent role change you made? If no, @miramar-labs we would need client logs from you, and you could do that by contacting our support team.

**Comment by sfc-gh-xhuang** [comment]
Closing as we have not heard back. 
Please let me know if you still run into this issue with the latest releases
