### ISSUE TITLE
[schematization] RECORD_METADATA mandatory even with "snowflake.metadata.all": "FALSE"

### ISSUE THREAD

**Issue by BDeus** [snowflakedb/snowflake-kafka-connector#697]
Hi,
i wondering if it is possible to not check the presence of the RECORD_METADATA column if `schematization` is on and `metadata.all` is false.
Currently the connector raise an error if the column does not exist on the destination table.
https://github.com/snowflakedb/snowflake-kafka-connector/blob/3526454ed557d26ac2fe0f93536f7755fa3b5494/src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java#L542

**Comment by sfc-gh-tzhang** [comment]
According to our documentation of snowflake.metadata.all, the RECORD_METADATA column still exists even if snowflake.metadata.all is set to FALSE

**Comment by BDeus** [comment]
Yes
I wondering if they are a possibility to disable the RECORD_METADATA as a feature request.
The feature request https://github.com/snowflakedb/snowflake-kafka-connector/issues/698 can also do the job to avoid possible colision naming.
Thanks
