### ISSUE TITLE
[feature request] Add the possibility to rename or not include the RECORD_METADATA column

### ISSUE THREAD

**Issue by BDeus** [snowflakedb/snowflake-kafka-connector#698]
Hi,
With schematization on, it's now possible to have colision on column name like `RECORD_METADATA`
Is it possible to consider a parameter to choose the name of the metadata column ?

**Comment by sfc-gh-xhuang** [comment]
Linking 
https://github.com/snowflakedb/snowflake-kafka-connector/issues/697

**Comment by sfc-gh-gjachimko** [comment]
@BDeus @sfc-gh-xhuang is this still required?

**Comment by sfc-gh-xhuang** [comment]
This is not something we will do for now
