### ISSUE TITLE
Prefix the channel name

### ISSUE THREAD

**Issue by BDeus** [snowflakedb/snowflake-kafka-connector#702]
Hi,
in rare scenario when we want to use two differents connectors from the same topic (with different snowflake table), 
the channel name disable this possibility because the channel name is set from the [source topic and partition](https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/internal/streaming/SnowflakeSinkServiceV2.java#L238).
Is it possible to have a prefix option in connector or use the (connector name hash + topic/partition) as channel name to avoid this issue ?

Furthermore, i read that is it possible [to reset offset from a channel](https://github.com/snowflakedb/snowflake-kafka-connector/issues/690#issuecomment-1691131315), but i cannot find how (changing connector name is not enough due to previous topic/partition channel name restriction).

Thanks for advice

**Comment by sfc-gh-japatel** [comment]
This is a legit feature request and we will work on it. Ideally, connector name and topic partition name should be enough..

**Comment by sfc-gh-xhuang** [comment]
> Furthermore, i read that is it possible https://github.com/snowflakedb/snowflake-kafka-connector/issues/690#issuecomment-1691131315, but i cannot find how (changing connector name is not enough due to previous topic/partition channel name restriction).

Here is the documentation
https://docs.snowflake.com/en/sql-reference/functions/system_snowpipe_streaming_update_channel_offset_token
