### ISSUE TITLE
Error inserting Records using Streaming API with msg:The given row cannot be converted to the internal format due to invalid value: Value cannot be ingested into Snowflake column BINARY_COL of type BINARY, Row Index: 0, reason: Not a valid hex string

### ISSUE THREAD

**Issue by acristu** [snowflakedb/snowflake-kafka-connector#704]
Hello,

Trying to ingest `binary_col` with schema `Schema.BYTES_SCHEMA` and value `new byte[]{1, 2, 3, 4, 5}` into snowflake and getting the above error.

Issue seems to stem from the RecordService converting the kafka record to the snowflake json record: https://github.com/snowflakedb/snowflake-kafka-connector/blob/3bf9106b22510c62068f7d2f7137b9e57989274c/src/main/java/com/snowflake/kafka/connector/records/RecordService.java#L470
Instead of converting to a hex string, which snowflake expects as input, the value is converted to base64 `AQIDBAU=`

As a workaround, in `RecordService.getMapFromJsonNodeForStreamingIngest` added the following:
```
      } else if (columnNode.isBinary()) {
        byte[] binaryValue = Base64.getDecoder().decode(columnNode.asText());
        columnValue = HexFormat.of().formatHex(binaryValue);
```
NOTE: using Java 17
NOTE: related issue #684

When using debezium as a source, `binary.handling.mode` can be set to `hex` but the kafka connect schema will be `string` and the column on snowflake side needs to be of type `BINARY`

**Comment by sfc-gh-rcheng** [comment]
Thanks for opening this. We have a possible fix, but I need to repro this locally to ensure this works. Will update with findings in a couple days

**Comment by sfc-gh-rcheng** [comment]
update: still trying to get a repro. I've been able to ingest the following sink record with both Streaming and Schematization enabled
```
SinkRecord record1 =
        new SinkRecord(
            topic,
            partition,
            Schema.BYTES_SCHEMA,
            new byte[]{1, 2, 3, 4, 5},
            Schema.BYTES_SCHEMA,
            new byte[]{1, 2, 3, 4, 5},
            offset);
```

**Comment by sfc-gh-rcheng** [comment]
@acristu would you or @JonathonO be able to repro and share your KC logs for this issue? I've tried numerous different inputs, but I've only been able to error out in Kafka Connector, not in the ingestSDK
