### ISSUE TITLE
Configuring temporal type formats with Snowpipe Streaming

### ISSUE THREAD

**Issue by ryzhyk** [snowflakedb/snowflake-kafka-connector#716]
I use the Snowflake Kafka connector with Snowpipe Streaming, setting `snowflake.enable.schematization` to `TRUE` to ingest structured data instead of raw JSON.  I don't have a schema registry (`"value.converter.schemas.enable":"false"`). Here is my exact configuration:

```json
{
        "name": "snowflake-test",
        "config": {
            "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
            "tasks.max": "8",
            "topics": "snowflake-test-topic3",
            "snowflake.ingestion.method": "SNOWPIPE_STREAMING",
            "snowflake.enable.schematization": "TRUE",
            "key.converter":"org.apache.kafka.connect.storage.StringConverter",
            "value.converter":"org.apache.kafka.connect.json.JsonConverter",
            "value.converter.schemas.enable":"false",
            "snowflake.url.name":"<account_name>.snowflakecomputing.com:443",
            "snowflake.user.name":"ci_1",
            "snowflake.role.name":"ci_role_1",
            "snowflake.private.key":"...",
            "snowflake.database.name":"test",
            "snowflake.schema.name":"test_schema",
            "buffer.flush.time":"1",
           "buffer.count.records":"10000"
        }
}
```

I created the target table by hand, so that fields in input JSON records get mapped into predefined columns. Some of these columns have temporal types, e.g., `TIMESTAMP`.  This works well, with records representing valid timestamp (e.g., `2013-04-28T20:57:01.123456789+07:00`) getting parsed into corresponding SQL types.

My question is whether there is a way to specify the exact format used for temporal columns, similar to how file formats can be specified for `COPY` commands. For instance I would like to specify that timestamps are encoded as `YYYY-MM-DD"T"HH24:MI:SS.FFTZH:TZM` instead of having Snowflake auto-detect the format.

**Comment by sfc-gh-tzhang** [comment]
I don't think we support this, but I guess you can do it with [SMT](https://docs.confluent.io/platform/current/connect/transforms/overview.html)?

**Comment by ryzhyk** [comment]
Thanks! So to clarify, the current behavior is that JSON records will be parsed as if all columns of the table were configure in the AUTO mode. Is that correct?

**Comment by sfc-gh-tzhang** [comment]
Yeah, I don't think we do anything fancy here, basically you create the TIMESTAMP column manually, then we use naming matching to put the data into corresponding column without any transformation. If you have any invalid timestamp format not in https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-overview#supported-java-data-types, the row will be rejected.
