### ISSUE TITLE
Transactional ingest

### ISSUE THREAD

**Issue by ryzhyk** [snowflakedb/snowflake-kafka-connector#717]
Is there a mechanism to ingest multiple Kafka messages in Snowflake atomically when using the `SNOWPIPE_STREAMING` ingestion method, so that all of them appear in the Snowflake table at the same time?

**Comment by ryzhyk** [comment]
Related question: does the connector guarantee that all records that arrive in the same Kafka message are ingested atomically, as part of a transaction?

**Comment by ryzhyk** [comment]
Understood, thank you!

**Comment by sfc-gh-azagrebin** [comment]
Thanks for the quick confirmation! I am closing this issue. Feel free to reopen if you think we can help more with this.
