### ISSUE TITLE
NDJSON support.

### ISSUE THREAD

**Issue by ryzhyk** [snowflakedb/snowflake-kafka-connector#719]
Does the Kafka connector support NDJSON or some other way to pack multiple JSON records in the same Kafka value when using `SNOWPIPE_STREAMING`? I have so far only been able to send one record per Kafka message.

**Comment by ryzhyk** [comment]
> @ryzhyk I'm just trying to understand the request here. Does your Kafka message stored in the topic contain multiple JSON objects delimited by a newline character, and you want those to be treated as separate rows in Snowflake instead?

yes

> It probably makes more sense to just have a single Kafka message with a single JSON object so you'll just end up with a higher number of messages but smaller in size, which is never a bad thing in Kafka.

This is what I ended up doing, thanks for confirming!

**Comment by sfc-gh-azagrebin** [comment]
@ryzhyk 
is your concern resolved? can we close this issue?

**Comment by ryzhyk** [comment]
yes
