### ISSUE TITLE
`buffer.flush.time` setting not working correctly.

### ISSUE THREAD

**Issue by ryzhyk** [snowflakedb/snowflake-kafka-connector#721]
Here is my complete connector config.  Note the `SNOWPIPE_STREAMING` ingestion method and the `"buffer.flush.time": "1"` setting, which, according to the [documentation](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka#buffer-and-polling-properties) should force the connector to flush its internal buffer to Snowflake every second:

```json
 {
        "name": "snowflake-demo",
        "config": {
            "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
            "tasks.max": "8",
            "topics": "snowflake.price,snowflake.preferred_vendor",
            "snowflake.topic2table.map": "snowflake.price:price,snowflake.preferred_vendor:preferred_vendor",
            "errors.tolerance": "all",
            "errors.deadletterqueue.topic.name": "snowflake-test-dlq",
            "errors.deadletterqueue.topic.replication.factor": "1",
            "errors.deadletterqueue.context.headers.enable": "true",
            "snowflake.ingestion.method": "SNOWPIPE_STREAMING",
            "snowflake.enable.schematization": "TRUE",
            "key.converter": "org.apache.kafka.connect.storage.StringConverter",
            "value.converter": "org.apache.kafka.connect.json.JsonConverter",
            "value.converter.schemas.enable": "false",
            "snowflake.url.name": "...",
            "snowflake.user.name": "ci_1",
            "snowflake.role.name": "ci_role_1",
            "snowflake.private.key": "...",
            "snowflake.private.key.passphrase": "...",
            "snowflake.database.name": "ci",
            "snowflake.schema.name": "test_schema",
            "buffer.flush.time": "1",
            "buffer.count.records": "10000",
        },
    }
```

In my experiment I feed several records to Kafka and monitor the contents of the target tables in Snowflake. I observe that it takes exactly one minute for the changes to appear in the target tables, which suggests that the `buffer.flush.time` setting isn't working.  But when I set `"buffer.count.records": "1"` to force the buffer to flush after each record, the Kafka-to-Snowflake latency drops to <5s.

Am I doing something wrong or does the `buffer.flush.time` setting not work as specified?

**Comment by sfc-gh-japatel** [comment]
Hi @ryzhyk the buffer.flush.time is honored only during the delivery message API in kafka connect. meaning the frequency of poll API. So if two polls occurrance took 60 seconds, you would see a 60 second lag even though flush time would have been set to 1 second. We currently don't have a background service which checks the flush time and inserts rows every second. For this to happen, there should be enough poll requests to kafka broker. Typically in a single poll there are 500 records. so if you are only inserting one record, 60 seconds latency is expected. -- max.poll.interval.ms is the config you want to play with

On the other hand for count.records = 1, if you are sending only one record, we will hit the threshold and call the ingestion API and you would see latency < 5seconds. 


Overall, the 60 seconds latency or more is typically observed only as tail latency in an ideal situation of streaming ingestion. 


Hope this helps. Thanks

**Comment by ryzhyk** [comment]
Thanks for the explanation.  Setting `max.poll.interval.ms` to 1000 does the trick for me!

**Comment by ryzhyk** [comment]
Re-opening this issue because using `max.poll.interval.ms` to control the frequency of polling Kafka doesn't seem like a great solution here.  To summarize what I've learned so far:

* I am trying to build near-realtime ingestion pipeline into Snowflake using the Kafka Connector and Snowpipe Streaming
* 
* I would like Kafka messages to be delivered with low latency even if there are only a few messages in the topic, i.e., I don't want to rely on the buffer in the connector filling up.

* @sfc-gh-japatel kindly explained that the `buffer.flush.time` setting only controls delivery latency _after_ the messages have been read from the Kafka topic, but doesn't affect the frequency of polling Kafka, which seems to be ~60s by default.

* Setting `max.poll.interval.ms` does seem to increase Kafka polling frequency, but my understanding is that this is not the intended purpose of this setting, which is to serve as a timeout to trigger group rebalancing if the client doesn't call `poll()`.  So while setting it to a low value does seem to cause the connector to poll Kafka more frequently, it also increases the chances of triggering spurious rebalancing when, e.g., the consumer is busy processing a large volume of messages.

Is the above summary accurate?  And if so, is there any other method I can use to convince the connector to poll Kafka more frequently?

Thank you!

**Comment by sfc-gh-japatel** [comment]
@ryzhyk that is correct understanding, if you'd like real time latency, I would encourage to keep buffer count threshold as low as possible. 
AFAIK, there are no other configs in kafka to poll more frequently. 

We would take the background flushing of buffered data as a feature request to not rely on poll frequency and honor the flush timestamp

**Comment by ryzhyk** [comment]
Many thanks for confirming!

> if you'd like real time latency, I would encourage to keep buffer count threshold as low as possible.

Isn't this going to adversely affect the performance of the connector when processing large volumes of messages?

> AFAIK, there are no other configs in kafka to poll more frequently.

This part is a bit confusing to me.  My understanding is that poll frequency is part of the internal logic of the connector, not Kafka itself, i.e., it's up to the connector to decide how long it should sleep before polling Kafka again. So there's no reason this should be a Kafka config option.

> We would take the background flushing of buffered data as a feature request to not rely on poll frequency and honor the flush timestamp

That'd be great. Is there a formal process to submit a feature request?  Should I create a separate issue for that?

Also, any chance you could point me to the relevant place in the code where the connector decides how long it should sleep before polling Kafka?

**Comment by sfc-gh-japatel** [comment]
By kafka, i mean kafka connect code. its not handleded in snowflake kafka connector. the framework decides when to send messages. https://github.com/apache/kafka/blob/trunk/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L587

**Comment by ryzhyk** [comment]
Ah, that makes sense.

**Comment by sfc-gh-azagrebin** [comment]
@ryzhyk
is your problem solved? can this be closed?

**Comment by ryzhyk** [comment]
My original question was answered, but based on the discussion with @sfc-gh-japatel (see above) this issue was tagged as a feature request.

**Comment by sfc-gh-japatel** [comment]
Closing this issue in lieu of feature request.
