### ISSUE TITLE
Struct array elements are being serialized before writing to Array column

### ISSUE THREAD

**Issue by cchandurkar** [snowflakedb/snowflake-kafka-connector#724]
I have a field in avro schema that is an Array of Struct type. Table has an existing column that's of Array type. I'm seeing array elements being serialized (Seeing array of stringified JSON in the SF column). Since the column is Array, it can take an array of object (struct/variant). Is there any way to disable this serialization and treat the elements as a variant instead?

Here's a quick comparison:
Expected value in column:
```json
[
  null,
  {
    "xCategory": null,
    "xEntityId": null,
    "xEntityName": null,
    "xId": "89asda9s0a"
  }
]
```

Actual:
```json
[
  "null",
  "{\"xCategory\":null,\"xEntityId\":null,\"xId\":\"89asda9s0a\",\"xEntityName\":null}"
]
```

**Comment by cchandurkar** [comment]
Was digging into the codebase. It looks like this [RecordService#getMapFromJsonNodeForStreamingIngest()](https://github.com/snowflakedb/snowflake-kafka-connector/blob/master/src/main/java/com/snowflake/kafka/connector/records/RecordService.java#L302) does not handle Struct and just stringifies it. Is this intentional? What if you recursively convert Struct into an ObjectNode?

**Comment by sfc-gh-azagrebin** [comment]
This is indeed not clear why to stringify array elements. SDK would indeed treat it as a string.
@sfc-gh-japatel @sfc-gh-tzhang wdyt?

@sfc-gh-zefan is it expected this way for Snowpipe?

**Comment by cchandurkar** [comment]
Closing at this is fixed in https://github.com/snowflakedb/snowflake-kafka-connector/pull/730.
