### ISSUE TITLE
Where is the 2.1.1 release?

### ISSUE THREAD

**Issue by sskirby** [snowflakedb/snowflake-kafka-connector#743]
I can see from the [commits](https://github.com/snowflakedb/snowflake-kafka-connector/commit/3f99a0703d83902082f5bfd8849e914a7fed1d06) and from the [Snowflake docs](https://docs.snowflake.com/en/user-guide/kafka-connector-monitor) that a 2.1 version of this project should exist.

However, the 2.1.1 version (or the 2.1.0 version) does not exist on the [Confluent Client Hub](https://www.confluent.io/hub/snowflakeinc/snowflake-kafka-connector) or in the [Github releases](https://github.com/snowflakedb/snowflake-kafka-connector/releases).

What's going on?

**Comment by sfc-gh-japatel** [comment]
Hi @sskirby 
We had issue with version 2.1.0 which had to be rolledback. To prevent any more usage of it, we had to remove it from GH release and confluent hub. 

We are working on version 2.1.1 as best as we can and will be very similar to the 2.1.0 with the fix. Stay tuned on the release!

**Comment by sskirby** [comment]
@sfc-gh-japatel thanks for the update!
