### ISSUE TITLE
Failure to properly deserialize decimal data type

### ISSUE THREAD

**Issue by jakemack** [snowflakedb/snowflake-kafka-connector#790]
This is likely a resurfacing of https://github.com/snowflakedb/snowflake-kafka-connector/issues/122 but I am creating a new issue since that was closed so long ago.

I am using version 2.2.0 of snowflake-kafka-connector. Here is my config with details redacted:

```
connector.class=com.snowflake.kafka.connector.SnowflakeSinkConnector
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=com.snowflake.kafka.connector.records.SnowflakeJsonConverter
snowflake.database.name=<db>
snowflake.schema.name=<schema>
snowflake.topic2table.map=<custom_mapping>
snowflake.private.key.passphrase=<passphrase>
tasks.max=30
topics=<topics_list>
snowflake.private.key=<key>
snowflake.user.name=<username>
snowflake.url.name=<url>
```

The data in the snowflake table includes the schema but for some reason does not deserialize the fields. I'll provide the relevant fields in the Snowflake table below.

```
{
  "payload": {
    "after": {
      "format_pageheight": "DByWAA==",
      ...
    },
    "before": null,
    "op": "r",
    "source": {
      ...
    },
    "transaction": null,
    "ts_ms": 1708417268440
  },
  "schema": {
    "fields": [
      {
        "field": "after",
        "fields": [
          {
            "field": "format_pageheight",
            "name": "org.apache.kafka.connect.data.Decimal",
            "optional": true,
            "parameters": {
              "connect.decimal.precision": "19",
              "scale": "6"
            },
            "type": "bytes",
            "version": 1
          },
          ...
        ],
        "name": "....Value",
        "optional": true,
        "type": "struct"
      },
      ...
    ],
    "name": "....Envelope",
    "optional": false,
    "type": "struct",
    "version": 1
  }
}
```

I was initially using `org.apache.kafka.connect.json.JsonConverter` as the `value.converter` as well but replication stopped when I hit tombstone records. Switching to `com.snowflake.kafka.connector.SnowflakeSinkConnector` for the `value.converter` fixed that but now this issue cropped up. I am sidestepping this issue by setting Debezium's connector config property `decimal.handling.mode` to "string" and then converting data back to decimal later in our pipeline.

**Comment by jakemack** [comment]
Thanks for the response. I did a little more research after your response and I believe I've found my disconnect.

I was using `org.apache.kafka.connect.json.JsonConverter` as my value converter in a source connector. In Kafka Connect, the default output for a decimal is binary BASE64 string encoding. Since I was initially using `org.apache.kafka.connect.json.JsonConverter` as the value converter in my sink connector, this use case was initially handled. My assumption was that the `com.snowflake.kafka.connector.SnowflakeSinkConnector` would be compatible with `org.apache.kafka.connect.json.JsonConverter` with the default settings. However, this is not the case. It seems I can set `decimal.format` to `numeric` to have my source connector output the value as a decimal number.

Here is my reference for my current understanding: https://cwiki.apache.org/confluence/display/KAFKA/KIP-481%3A+SerDe+Improvements+for+Connect+Decimal+type+in+JSON

All that said, I'd imagine either a) mentioning this incompatibility in the docs for the Snowflake Kafka Connector or b) being able to handle this Base64 encoding case would be very helpful for a bunch of people.

**Comment by jakemack** [comment]
Thanks for the update! I actually just switched us to Snowpipe Streaming and we're now using `org.apache.kafka.connect.json.JsonConverter` with `value.converter.decimal.format` set to `numeric`.

We can close this issue since there are known workarounds and there isn't a plan to support this specific use case.

**Comment by Jaideep-C** [comment]
> org.apache.kafka.connect.json.JsonConverter with value.converter.decimal.format set to numeric.

Hi @jakemack Where should we specify the `value.converter.decimal.format` to `numeric`? in our case we are using Kafka connect and we are using `org.apache.kafka.connect.json.JsonConverter` as the serialize in the source connector.
