### ISSUE TITLE
Rollback on Prefix with channel name with connector name

### ISSUE THREAD

**Issue by BDeus** [snowflakedb/snowflake-kafka-connector#810]
Hi,
It seems the PR https://github.com/snowflakedb/snowflake-kafka-connector/pull/751 rollback the feature https://github.com/snowflakedb/snowflake-kafka-connector/pull/703. Was this intended ?
If it is, can we create a configuration option to condition channel name (like my previous request https://github.com/snowflakedb/snowflake-kafka-connector/issues/702)  

Currently it is not possible to delete a channel (just upgrade offset throw SYSTEM function). In case of topic recreation the offsets on channel won't follow.
We could use the prefix configuration as a bypass for that.
Thanks

**Comment by sfc-gh-xhuang** [comment]
The rollback was intended as changing the channel name by default could cause topics to get confused. 

It will have to be opt-in instead of opt-out
