### ISSUE TITLE
Can i point Kafka record to snowflake table's column directly, just like we use snowflaketopic2table, do we have snowflakerecord2column config?

### ISSUE THREAD

**Issue by PavanKalyan97** [snowflakedb/snowflake-kafka-connector#814]
Hi Team, 

i have snowflake table with ID and Name as columns,

is there any way i can point my kafka topic record id to be inserted into table's column named ID directly and "Name" record to "Name" column.
i see 2 columns automatically created by default, record metadata and record content.

is there any way i can do some filteration?

Your response is appreciated.
Thanks,
Pavan

**Comment by sfc-gh-lshcharbaty** [comment]
Hi Pavan, 
It seems you're looking for [Schema Detection and Evolution](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka-schema-detection).

**Comment by PavanKalyan97** [comment]
Hello Sir,
Thanks for the link , let me try it out and post an update.

**Comment by sfc-gh-akowalczyk** [comment]
No further activity in this topic
