### ISSUE TITLE
AWS Glue Schema Registry compatability

### ISSUE THREAD

**Issue by tomellis91** [snowflakedb/snowflake-kafka-connector#823]
Is it possible to use the AWS Glue Schema registry with this plugin? 

From what I have found so far it doesn't look to expose a URL and only uses native AWS Endpoints for access. This means  we are unable to populate the `value.converter.schema.registry.url` and will need to roll our own schema registry to use MSK connect. 

If it isn't possible, is this something that will be considered to be added as an additional configuration?

**Comment by sfc-gh-gjachimko** [comment]
Let me check it with the devs and we will get back to you.

**Comment by sfc-gh-gjachimko** [comment]
Hi
So - it is possible to configure our plugin with AWS Glue. 
There some additional steps required though - you need to bundle the plugin with the proper JAR containing valid converter. You didn't specify which data format you'd like to use, so here are the options:

- https://mvnrepository.com/artifact/software.amazon.glue/jsonschema-kafkaconnect-converter
- https://mvnrepository.com/artifact/software.amazon.glue/protobuf-kafkaconnect-converter
- https://mvnrepository.com/artifact/software.amazon.glue/schema-registry-kafkaconnect-converter

Having these two pieces bundled together, please follow AWS guideline on creating plugin: https://docs.aws.amazon.com/msk/latest/developerguide/msk-connect-plugins.html

Setting up the MSK connector will require proper IAM role - https://docs.aws.amazon.com/msk/latest/developerguide/mkc-tutorial-setup.html.

Then, you will need to configure MSK [worker](https://docs.aws.amazon.com/msk/latest/developerguide/msk-connect-workers.html) and [connector](https://docs.aws.amazon.com/msk/latest/developerguide/msk-connect-connectors.html).

From the connector perspective, the important piece of functionality to make it work with AWS is the following:
`value.converter.schemas.enable=true
value.converter.region=<aws region>
value.converter.schemaAutoRegistrationEnabled=true
value.converter.dataFormat=<your format specifier>
value.converter.registry.name=<AWS Glue Regisry Name>`

In case of further issues, please feel free to reach out or contact our support.

**Comment by tomellis91** [comment]
thank you @sfc-gh-gjachimko 🙌 I will try this out.
