### ISSUE TITLE
Automatically create a table based on Avro schema

### ISSUE THREAD

**Issue by MaximBogun** [snowflakedb/snowflake-kafka-connector#829]
Hello,

I am attempting to use the managed Snowflake sink from Confluent and am looking for a way to automatically create a table based on the Avro schema. 

My question is: Is it possible to automatically create a table with fields using the Avro schema? 

I am aware that I can manually create a table and map fields to it, but that is not the solution I am seeking. I would like to see, for example, `id, name, last_name` and all of this created automatically as columns, not inside the `data` column. 

If this is not possible, please let me know. 
Thank you.

**Comment by sfc-gh-xhuang** [comment]
Yes it is possible if you use Snowpipe Streaming as the ingestion.method. 

See this doc: https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-kafka-schema-detection

**Comment by sfc-gh-xhuang** [comment]
Closing, please feel free to reopen if you need more help
