### ISSUE TITLE
30X Snowpipe usage compared to AWS Snowpipe

### ISSUE THREAD

**Issue by xiekevin** [snowflakedb/snowflake-kafka-connector#83]
I've tried to use the snowflake kafka connector and it works great with version 0.5.5 but the issue is that the data imported is not as compressed as the data imported via S3 (60B vs 144B per row calculated with a total data pool of 1.7TB and 20GB respectively) and the snowpipe credit usage is 30X what it is while using AWS snowpipe following this tutorial (https://docs.snowflake.net/manuals/user-guide/data-load-snowpipe-auto-s3.html)

Right now on average we're spending slightly over 1 credit per day to load the data via S3 through our old pipeline, but running the snowflake kafka connector for 8 hours has already cost us close to 10 credits. This is nearly a 30X increase as prorated the rest of the day we would be spending 30 credits.

Are there any optimizations that can be made to avoid this and make data transfer more efficient? It seems like the connector makes a stage on S3 so I'm a little confused by the vast increase in cost.

**Comment by binglihub** [comment]
You can adjust `buffer.count.records`, `buffer.flush.time` and  `buffer.size.bytes` parameters to group more records together. 
https://docs.snowflake.net/manuals/user-guide/kafka-connector-install.html#label-kafka-properties

**Comment by binglihub** [comment]
We now support meta data content adjustment. In your case, you may need remove some meta data to save the snowpipe cost.
https://github.com/snowflakedb/snowflake-kafka-connector/pull/102
