### ISSUE TITLE
A record_timestamp column

### ISSUE THREAD

**Issue by yportnoy** [snowflakedb/snowflake-kafka-connector#84]
We are using the connector in production but we find that we have to rely on user created timestamps or Kafka timestamps for ETL which isn't great. We want to be able to use the timestamp of when each record gets written down in Snowflake. In order to do that we currently have to alter each KafkaConnect created table in Snowflake with `default current_timestamp()` as the value of the record_timestamp . The problem, of course, is that it's an asynchronous operation. We would find it very useful if the connector could create this column by itself or there was a mechanism for creating this third column with the connector configuration

**Comment by NarekDW** [comment]
@yportnoy Did you consider solution with Kafka Connect Transformations?
In particular you could take a look at  [InsertField Transformer](https://docs.confluent.io/current/connect/transforms/insertfield.html#insertfield) to enhance your message with timestamp field.

**Comment by Stormhand** [comment]
> @yportnoy Did you consider solution with Kafka Connect Transformations?
> In particular you could take a look at [InsertField Transformer](https://docs.confluent.io/current/connect/transforms/insertfield.html#insertfield) to enhance your message with timestamp field.

You can't use row transformations with snowflake connector

**Comment by NarekDW** [comment]
> > @yportnoy Did you consider solution with Kafka Connect Transformations?
> > In particular you could take a look at [InsertField Transformer](https://docs.confluent.io/current/connect/transforms/insertfield.html#insertfield) to enhance your message with timestamp field.
> 
> You can't use row transformations with snowflake connector

Could you explain, please?
Why isn't it possible to use Kafka Connect Transformers with Snowflake Connector?
Snowflake Connector is a Sink Connector, and as I know it's possible to use it with Transformers.

**Comment by Stormhand** [comment]
https://docs.snowflake.net/manuals/user-guide/kafka-connector-overview.html

> Currently, the Kafka connector does not work with Single Message Transformations (SMTs). SMTs are applied to messages as they flow through Kafka Connect. For more information about this feature, see https://docs.confluent.io/current/connect/transforms/index.html

**Comment by rumbin** [comment]
A load timestamp and an auto-incrementing row_id are must-haves in my eyes for further incremental processing.
Such a pitty that this issue does not get any attention for this long time :-(

**Comment by chwebdude** [comment]
Same here. This should be essential

**Comment by pcb-submittable** [comment]
This would be a huge win for us too. 

Since our topics have `.` in them (and again, without SMTs we can't rename them), the tables generated have a hash. So ours workflow requires a further step where we must:
1. First run the connector against the topic to see what the generated table's name is going to be. 
2. Delete the table and recreate it with ETL_LAST_UPDATED column
3. Restart the sink starting from beginning of topic

**Comment by sfc-gh-japatel** [comment]
Hello all, apologies for late response. For more accurate results for timestamps when record is ingested into snowflake, we could use copy_history's https://docs.snowflake.com/en/sql-reference/functions/copy_history.html LAST_LOAD_TIME field. 

I know it is not the most straightforward option given the fact that we couldnt use SMT. Even if SMTs are supported, it wouldnt be possible to add a column to the target column.

**Comment by rumbin** [comment]
@sfc-gh-tzhang why have you closed this issue? Is it fixed?

**Comment by pcb-submittable** [comment]
Not sure if this helps, but I modified the connector to support a `row_updated_at` column. However, I haven't had a chance to get the PR up. I'll try to get it out in a few weeks after I fix a test or two.

**Comment by sfc-gh-tzhang** [comment]
@rumbin I believe a few work arounds are provided in this thread already. If none of them works for you, please submit a feature request through Snowflake Support/Sales so we could better tracking and prioritizing it.
