### ISSUE TITLE
Add Schema Registry Documentation to Snowflake Column Comments

### ISSUE THREAD

**Issue by wornjs** [snowflakedb/snowflake-kafka-connector#846]
When creating tables using the Snowflake Kafka Connector, the column comment is always set to "created by schema evolution from Snowflake Kafka Connector". If there is information available in the Schema Registry's connect.doc, we should use that value as the column comment instead.

Example:

When using Debezium to capture CDC (Change Data Capture) data, column comments are stored in the Schema Registry. By utilizing these comments, we can ensure that the column comments in Snowflake match the original database comments exactly. This would improve the consistency and readability of the data schema.

Benefits:
- Improved consistency between source and target schemas
- Enhanced readability and understanding of column purposes
- More informative column comments in Snowflake tables

Proposed Change:
- Modify the Snowflake Kafka Connector to check for connect.doc values in the Schema Registry.
- If a connect.doc value exists, use it as the column comment.
- If no connect.doc value is available, default to the current comment "created by schema evolution from Snowflake Kafka Connector".

**Comment by sfc-gh-akowalczyk** [comment]
The PR is already merged
https://github.com/snowflakedb/snowflake-kafka-connector/pull/847
https://github.com/snowflakedb/snowflake-kafka-connector/pull/870

Thank you, @wornjs, for the contribution.
