### ISSUE TITLE
The Snowflake Avro Value Converter silently skips messages it can't decode

### ISSUE THREAD

**Issue by yarmiganosca** [snowflakedb/snowflake-kafka-connector#86]
As far as I can tell, if a Snowflake Connector configured to use the Snowflake Avro Converter encounters a message it can't decode, nothing is written to logs, and it skips the message with no external indication. This is extremely frustrating for debugging.

If we could even have just a message that said something like "the message at topic/partition/offset was discarded because it couldn't be decoded" (no need to include the message contents, since it might be huge, and the topic/partition/offset combo lets me investigate it if I want to) would be tremendously helpful.

**Comment by sfc-gh-zli** [comment]
This https://github.com/snowflakedb/snowflake-kafka-connector/pull/171 PR would enable the connector to support non-snowflake converters. If you use native json/avro converters, DLQ is naturally supported. That could be a walk-around of this problem. 
Add loggings of broken record to Snowflake Converters could be an improvement on our todo list.

**Comment by raphaelauv** [comment]
@yarmiganosca is this still occurring ?

**Comment by morhook** [comment]
I _think_ this is not happening anymore.

**Comment by raphaelauv** [comment]
from the code I see that only in DEBUG mode the connect log when it can't decode an event

https://github.com/snowflakedb/snowflake-kafka-connector/blob/1f793adcf430b6993376324df58c4001e7096f0c/src/main/java/com/snowflake/kafka/connector/internal/FileNameUtils.java#L82

And the connector will continue to consume the partition without failing

https://github.com/snowflakedb/snowflake-kafka-connector/blob/1f793adcf430b6993376324df58c4001e7096f0c/src/main/java/com/snowflake/kafka/connector/internal/SnowflakeSinkServiceV1.java#L511

**Comment by raphaelauv** [comment]
@sfc-gh-tzhang could share with us why you closed that issue , thanks

**Comment by sfc-gh-tzhang** [comment]
@raphaelauv I believe the original question was answered and now we're uploading the broken record to a table stage, is there anything else you want from this thread?
