### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/provider/BouncyCastleFipsProvider (solved)

### ISSUE THREAD

**Issue by ronenb75** [snowflakedb/snowflake-kafka-connector#888]
Been looking around and already made sure both `bc-fips-1.0.1.jar` are `bcpkix-fips-1.0.3.jar` are in the same location as `snowflake-kafka-connector-2.3.0.jar` is.

Moreover, when I run
`/opt/bin/connect-standalone.sh /opt/config/connect-standalone.properties /opt/config/SF_connect.properties`, I can see the Bouncy Castle loading:
```
...
INFO Loading plugin from: /opt/bin/libs/snowflake-kafka-connector-2.3.0.jar (org.apache.kafka.connect.runtime.isolation.PluginScanner:75)
...
INFO Loading plugin from: /opt/bin/libs/bc-fips-1.0.1.jar (org.apache.kafka.connect.runtime.isolation.PluginScanner:75)
...
INFO Loading plugin from: /opt/bin/libs/bcpkix-fips-1.0.3.jar (org.apache.kafka.connect.runtime.isolation.PluginScanner:75)
...
```

Any ideas why I still get issues with Bouncy Casble classes?

My setup is pretty simple:
`Dockerfile`:
```
FROM oraclelinux:9

RUN <<EOF
	yum -y update
	yum -y install vim less wget git

    echo "alias ll='ls -lha --color'" >> /root/.bashrc
    echo "alias vi='vim'" >> /root/.bashrc
    echo "PS1=\"\[\\e[1;32m\][\h \w] >>>>> \[\\e[0m\]\"" >> /root/.bashrc
EOF

RUN <<EOL
	# Installing requirements for Kafka
	yum install -y java-21-openjdk

	# Download and extract Kafka
	cd /tmp
	wget https://downloads.apache.org/kafka/3.7.1/kafka_2.13-3.7.1.tgz
	tar -zxvf kafka_2.13-3.7.1.tgz -C /tmp
	mv /tmp/kafka_2.13-3.7.1/* /opt/
EOL

RUN <<EOL
# Download Snowflake Kafka Connector to allow hooking up Kafka connect to Snowfalke
# https://docs.snowflake.com/en/user-guide/kafka-connector-install
	mkdir /opt/bin/libs/
	cd /opt/bin/libs/
	wget https://repo1.maven.org/maven2/com/snowflake/snowflake-kafka-connector/2.3.0/snowflake-kafka-connector-2.3.0.jar

	# Download Bouncy Castle jars to allow encrypted private keys
	# https://docs.snowflake.com/en/user-guide/kafka-connector-install#installing-the-connector-for-confluent
	wget https://repo1.maven.org/maven2/org/bouncycastle/bc-fips/1.0.1/bc-fips-1.0.1.jar
	wget https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-fips/1.0.3/bcpkix-fips-1.0.3.jar
EOL

COPY --chmod=755 ./build/docker-entrypoint.sh /docker-entrypoint.sh
```

`connect-standalone.properties`:
```
plugin.path=/opt/bin/libs

# Kafka Security settings
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="snowflakeconnector" password="xxxxxxxx";
ssl.truststore.location=/opt/keys/kafka.client.truststore.jks
ssl.truststore.password=***
ssl.endpoint.identification.algorithm=


consumer.sasl.mechanism=PLAIN
consumer.security.protocol=SASL_SSL
consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="snowflakeconnector" password="xxxxxxxx";
consumer.ssl.truststore.location=/opt/keys/kafka.client.truststore.jks
consumer.ssl.truststore.password=***
consumer.ssl.endpoint.identification.algorithm=
```

`SF_connect.properties`:
```
name=snowpipe_streaming_ingest
connector.class=com.snowflake.kafka.connector.SnowflakeSinkConnector
tasks.max=8
topics=replicationEvents
snowflake.topic2table.map= replicationEvents:table1
buffer.count.records=10000
buffer.flush.time=60
buffer.size.bytes=5000000
snowflake.url.name=myorganization-myaccount.snowflakecomputing.com:443
snowflake.user.name=jane.smith
snowflake.private.key=MIIFLTBXBgkqhki.......
snowflake.private.key.passphrase=test
snowflake.database.name=mydb
snowflake.schema.name=myschema
snowflake.ingestion.method=SNOWPIPE_STREAMING
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=com.snowflake.kafka.connector.records.SnowflakeJsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
```

**Comment by sfc-gh-wfateem** [comment]
Hi @ronenb75,

You won't be able to use the Bouncy Castle FIPS provider unless you explicitly add that as a security provider in the JVM. You either do that by code:
```
import java.security.Security
import org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider

Security.addProvider(new BouncyCastleFipsProvider())
```
Or, by editing your java.security file:
```
security.provider.<n>=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
```
Where `<n>` is an integer denoting its order in the list of providers. You can find this information in the Bouncy Castle documentation [here](https://github.com/indrabasak/bouncycastle-fips-examples/blob/master/README.md).

The easiest solution in your case is to simply use the snowflake-kafka-connector-2.3.0.jar as-is without adding a Bouncy Castle library in your plugin path. That JAR includes the non-FIPS Bouncy Castle Provider, and it's only used to decrypt the private key.

**Comment by ronenb75** [comment]
Thank you @sfc-gh-wfateem,

I removed both `bc-fips-1.0.1.jar` and `bcpkix-fips-1.0.3.jar` from the location where `snowflake-kafka-connector-2.3.0.jar` is, leaving it to be the only jar.

It is loading:
```
INFO Loading plugin from: /opt/bin/libs/snowflake-kafka-connector-2.3.0.jar (org.apache.kafka.connect.runtime.isolation.PluginScanner:75)
```

But the same error is still there:
```
ava.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/provider/BouncyCastleFipsProvider
```

BTW, when I use an encrypted private key, the same setup works with no issue.
Am I missing anything?
Is my config somewho suggest I need FIPS compliance?

I created the key the way it's documented:
```
openssl genrsa -out rsa_key.pem 2048
openssl genrsa 2048 | openssl pkcs8 -topk8 -v2 aes256 -inform PEM -out rsa_key.p8
openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub
```

**Comment by sfc-gh-wfateem** [comment]
Hi @ronenb75,

I'll take a closer look at the code. Based on your dockerfile, I would say there's some code that's explicitly adding `BouncyCastleFipsProvider` as a security provider programmatically.

Was there a full stack with that error by any chance? If so, can you paste that here, please?

**Comment by sfc-gh-wfateem** [comment]
I see we're explicitly adding the `BouncyCastleFipsProvider` security provider, but I ran a test using Apache Kafka 3.7.1 with the Snowflake Kafka Connector v2.3.0 and I'm not running into the same issue. I didn't add any Bouncy Castle FIPS Jars on the classpath either.

Can you provide the full stack for that error, please?

Also, did you publish this Docker image by any chance so I can see if I'm able to reproduce it locally that way?

Can you add the JVM argument `-verbose:class` and reproduce the problem then share the output from that classloading traces, please?

You will need to add the following instruction in your dockerfile:
`ENV KAFKA_OPTS -verbose:class` or provide that when you start your container:
`docker container run .... -e KAFKA_OPTS=-verbose:class <image>`

**Comment by sfc-gh-wfateem** [comment]
@ronenb75 actually, I spoke too soon. My test was actually running against Kafka 3.4.1. I'm able to reproduce it with Kafka v3.7.1. 
That tells me that likely what's happening here is that the classpath changed between Apache Kafka 3.4.1 and 3.7.1, where the BouncyCastleFipsProvider could be loaded in v3.4.1 but not v3.7.1. 
I'll take a closer look at that theory and get back to you with my findings. In the meantime, if you were just trying to do some testing and the Apache Kafka version is not immediately important, then try downgrading Apache Kafka to v3.4.1 in your docker image.

**Comment by sfc-gh-wfateem** [comment]
@ronenb75 It looks like both `bc-fips-1.0.2.1.jar` and `bcpkix-fips-1.0.5.jar` were included in the libs folder under the Kafka's home directory in v3.4.1 but they don't exist in 3.7.1 which explains why we get a ClassNotFoundException error in v3.7.1 if we don't include the Bouncy Castle FIPS JARs. 

All you need to do is set your plugin.path to point to a directory, then under that create a separate folder for your Snowflake Kafka connector and all its dependencies. For example:
```
plugin.path=/PLUGIN_PATH/lib
```
Under `PLUGIN_PATH/lib` create a folder called `snowflake` for example, then add the following JARs to it:
`PLUGIN_PATH/lib/snowflake/`:
```
snowflake-kafka-connector-2.3.0.jar
bc-fips-1.0.2.1.jar
bcpkix-fips-1.0.5.jar
```

It's structured in this manner in order to isolate each connector, so initially when you had those three JARs under the root `plugin.path` directory, Kafka Connect used one ClassLoader to load the classes from the `snowflake-kafka-connector-2.3.0.jar` and it expects all its dependencies to be included in that same JAR. It's going to treat every JAR under here as a unique plugin each having their own ClassLoader. Once you create a folder under `plugin.path` and put the connector along with the dependencies, a single ClassLoader will be used to load classes from all the JARs located in that folder, so it won't have any problems loading the `BouncyCastleFipsProvider` class. The `connect-standalone.properties` has the following comment mentioning this expectation:
```
# Set to a list of filesystem paths separated by commas (,) to enable class loading isolation for plugins
# (connectors, converters, transformations). The list should consist of top level directories that include
# any combination of:
# a) directories immediately containing jars with plugins and their dependencies
# b) uber-jars with plugins and their dependencies
# c) directories immediately containing the package directory structure of classes of plugins and their dependencies
```

Hope this helps!

**Comment by ronenb75** [comment]
Hey @sfc-gh-wfateem,

**You rock!**
That solved the issue.

As soon as I moved the 3 .jar into a sub-directory, keeping the `plugin.path` to the parent directory - it worked treat!

I will add my setup here for other if they would like to use it.

I'll upload my setup to my git: https://github.com/ronenb75/kafkaSASL_SSLConnectSF
It's a very simple setup of a Docker image running Kafka + SASL_SSL + ACLs + Snowflake Kafka connector + Encrypted Private Key (Bouncy Castle)

Kafka starts with docker-entrypoint, but the connector requires manual start (will change that to start with superviosrd)
`/opt/bin/connect-standalone.sh /opt/config/connect-standalone.properties /opt/config/SF_connect.properties`
