### ISSUE TITLE
Connector reading from many topics/partitions doesn't work in 2.5.0

### ISSUE THREAD

**Issue by alonpr** [snowflakedb/snowflake-kafka-connector#997]
I have a connector that reads from 1079 topics with 1 partition each and using the snowpipe ingestion method. Versions from 2.0.0 up to 2.4.1 work fine. When upgraded to 2.5.0 this connector doesn't get to start sending files. The consumer group after a while goes from "stable" to empty", then again back to "stable" and after a while to "empty" and so on. No error messages in the log.
Other connectors in the same kafka connect cluster, that read from less topics/partitions work fine on 2.5.0
This is the ful config of the connector:
```
{
        "snowflake.database.name": "prod",
        "topics.regex": "^xxxxxx_prod.*$",
        "snowflake.url.name": "xxxxxxxxxxx.privatelink.snowflakecomputing.com",
        "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",        
        "snowflake.user.name": "kafka_connector",
        "snowflake.private.key": "${file:/kafka/config/secrets.properties:SNOWFLAKE_PROD_CONNECTOR_PRIVATE_KEY}",
        "snowflake.schema.name": "changelog",
        "key.converter": "com.snowflake.kafka.connector.records.SnowflakeJsonConverter",
        "value.converter": "com.snowflake.kafka.connector.records.SnowflakeJsonConverter",
        "tasks.max": "1",
        "buffer.flush.time": "600",
        "buffer.count.records": "1000000000",
        "buffer.size.bytes": "500000000"
}
```

**Comment by sfc-gh-gjachimko** [comment]
@alonpr thank you for the report, could you report it please via https://docs.snowflake.com/user-guide/contacting-support ? 
In order to proceed, we'd need to collect more account data and look into your telemetry.
Also, would it be possible for you to attach whatever logs you could gather?

**Comment by sfc-gh-gjachimko** [comment]
I've checked the change log for the connector - there might be one change you might be observing - related to internal channel naming. There is potential race condition, when `topics.regex` is used, one task could claim ownership of stage file belonging to a different task. However, in your configuration - when you have 1 task supporting all the topics this is not the case. 

Could you give the connector a try with this configuration option:

`"snowflake.snowpipe.stageFileNameExtensionEnabled": "false"`

?

Still, I'd encourage you to raise a proper support ticket, as I'm really curious to get to the bottom of the problem and for that purpose - I need some additional information about your account.

**Comment by alonpr** [comment]
Hi @sfc-gh-gjachimko ,

I uploaded a relevant information to support ticket 00890530.

Thanks.

**Comment by sfc-gh-mbobowski** [comment]
Closing as there is a support ticket.
